package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA



/**
 * TblantecedentesDonante generated by hbm2java
 */
public class TblantecedentesDonante  implements java.io.Serializable {


     private Long idAntecedentesDonantes;
     private Tblevaluaciondonante tblevaluaciondonante;
     private int totalDonaciones;
     private int donacionesAnuales;
     private Boolean donantePrimerizo;
     private Boolean donanteVoluntario;
     private Boolean donanteHabitual;
     private String lugarDonacion;

    public TblantecedentesDonante() {
    }

	
    public TblantecedentesDonante(Tblevaluaciondonante tblevaluaciondonante, int totalDonaciones, int donacionesAnuales, String lugarDonacion) {
        this.tblevaluaciondonante = tblevaluaciondonante;
        this.totalDonaciones = totalDonaciones;
        this.donacionesAnuales = donacionesAnuales;
        this.lugarDonacion = lugarDonacion;
    }
    public TblantecedentesDonante(Tblevaluaciondonante tblevaluaciondonante, int totalDonaciones, int donacionesAnuales, Boolean donantePrimerizo, Boolean donanteVoluntario, Boolean donanteHabitual, String lugarDonacion) {
       this.tblevaluaciondonante = tblevaluaciondonante;
       this.totalDonaciones = totalDonaciones;
       this.donacionesAnuales = donacionesAnuales;
       this.donantePrimerizo = donantePrimerizo;
       this.donanteVoluntario = donanteVoluntario;
       this.donanteHabitual = donanteHabitual;
       this.lugarDonacion = lugarDonacion;
    }
   
    public Long getIdAntecedentesDonantes() {
        return this.idAntecedentesDonantes;
    }
    
    public void setIdAntecedentesDonantes(Long idAntecedentesDonantes) {
        this.idAntecedentesDonantes = idAntecedentesDonantes;
    }
    public Tblevaluaciondonante getTblevaluaciondonante() {
        return this.tblevaluaciondonante;
    }
    
    public void setTblevaluaciondonante(Tblevaluaciondonante tblevaluaciondonante) {
        this.tblevaluaciondonante = tblevaluaciondonante;
    }
    public int getTotalDonaciones() {
        return this.totalDonaciones;
    }
    
    public void setTotalDonaciones(int totalDonaciones) {
        this.totalDonaciones = totalDonaciones;
    }
    public int getDonacionesAnuales() {
        return this.donacionesAnuales;
    }
    
    public void setDonacionesAnuales(int donacionesAnuales) {
        this.donacionesAnuales = donacionesAnuales;
    }
    public Boolean getDonantePrimerizo() {
        return this.donantePrimerizo;
    }
    
    public void setDonantePrimerizo(Boolean donantePrimerizo) {
        this.donantePrimerizo = donantePrimerizo;
    }
    public Boolean getDonanteVoluntario() {
        return this.donanteVoluntario;
    }
    
    public void setDonanteVoluntario(Boolean donanteVoluntario) {
        this.donanteVoluntario = donanteVoluntario;
    }
    public Boolean getDonanteHabitual() {
        return this.donanteHabitual;
    }
    
    public void setDonanteHabitual(Boolean donanteHabitual) {
        this.donanteHabitual = donanteHabitual;
    }
    public String getLugarDonacion() {
        return this.lugarDonacion;
    }
    
    public void setLugarDonacion(String lugarDonacion) {
        this.lugarDonacion = lugarDonacion;
    }




}


