package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tblarticulo generated by hbm2java
 */
public class Tblarticulo  implements java.io.Serializable {


     private Integer idArticulo;
     private Tblunidadmedida tblunidadmedidaByUnidadMinimoUso;
     private Tblcatalogo tblcatalogo;
     private Tblunidadmedida tblunidadmedidaByUnidadMinimoCompra;
     private String codigoArticulo;
     private String nombreArticulo;
     private String presentacion;
     private double cantidadMinimaUso;
     private double cantidadMinimaCompra;
     private double existencias;
     private boolean perecedero;
     private double factorConversion;
     private String relacion;
     private boolean usoCompartido;
     private Set tbldetallepedidos = new HashSet(0);
     private Set tblmovimientos = new HashSet(0);
     private Set tblexamenarticulos = new HashSet(0);

    public Tblarticulo() {
    }

	
    public Tblarticulo(Tblunidadmedida tblunidadmedidaByUnidadMinimoUso, Tblcatalogo tblcatalogo, Tblunidadmedida tblunidadmedidaByUnidadMinimoCompra, String codigoArticulo, String nombreArticulo, String presentacion, double cantidadMinimaUso, double cantidadMinimaCompra, double existencias, boolean perecedero, double factorConversion, String relacion, boolean usoCompartido) {
        this.tblunidadmedidaByUnidadMinimoUso = tblunidadmedidaByUnidadMinimoUso;
        this.tblcatalogo = tblcatalogo;
        this.tblunidadmedidaByUnidadMinimoCompra = tblunidadmedidaByUnidadMinimoCompra;
        this.codigoArticulo = codigoArticulo;
        this.nombreArticulo = nombreArticulo;
        this.presentacion = presentacion;
        this.cantidadMinimaUso = cantidadMinimaUso;
        this.cantidadMinimaCompra = cantidadMinimaCompra;
        this.existencias = existencias;
        this.perecedero = perecedero;
        this.factorConversion = factorConversion;
        this.relacion = relacion;
        this.usoCompartido = usoCompartido;
    }
    public Tblarticulo(Tblunidadmedida tblunidadmedidaByUnidadMinimoUso, Tblcatalogo tblcatalogo, Tblunidadmedida tblunidadmedidaByUnidadMinimoCompra, String codigoArticulo, String nombreArticulo, String presentacion, double cantidadMinimaUso, double cantidadMinimaCompra, double existencias, boolean perecedero, double factorConversion, String relacion, boolean usoCompartido, Set tbldetallepedidos, Set tblmovimientos, Set tblexamenarticulos) {
       this.tblunidadmedidaByUnidadMinimoUso = tblunidadmedidaByUnidadMinimoUso;
       this.tblcatalogo = tblcatalogo;
       this.tblunidadmedidaByUnidadMinimoCompra = tblunidadmedidaByUnidadMinimoCompra;
       this.codigoArticulo = codigoArticulo;
       this.nombreArticulo = nombreArticulo;
       this.presentacion = presentacion;
       this.cantidadMinimaUso = cantidadMinimaUso;
       this.cantidadMinimaCompra = cantidadMinimaCompra;
       this.existencias = existencias;
       this.perecedero = perecedero;
       this.factorConversion = factorConversion;
       this.relacion = relacion;
       this.usoCompartido = usoCompartido;
       this.tbldetallepedidos = tbldetallepedidos;
       this.tblmovimientos = tblmovimientos;
       this.tblexamenarticulos = tblexamenarticulos;
    }
   
    public Integer getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(Integer idArticulo) {
        this.idArticulo = idArticulo;
    }
    public Tblunidadmedida getTblunidadmedidaByUnidadMinimoUso() {
        return this.tblunidadmedidaByUnidadMinimoUso;
    }
    
    public void setTblunidadmedidaByUnidadMinimoUso(Tblunidadmedida tblunidadmedidaByUnidadMinimoUso) {
        this.tblunidadmedidaByUnidadMinimoUso = tblunidadmedidaByUnidadMinimoUso;
    }
    public Tblcatalogo getTblcatalogo() {
        return this.tblcatalogo;
    }
    
    public void setTblcatalogo(Tblcatalogo tblcatalogo) {
        this.tblcatalogo = tblcatalogo;
    }
    public Tblunidadmedida getTblunidadmedidaByUnidadMinimoCompra() {
        return this.tblunidadmedidaByUnidadMinimoCompra;
    }
    
    public void setTblunidadmedidaByUnidadMinimoCompra(Tblunidadmedida tblunidadmedidaByUnidadMinimoCompra) {
        this.tblunidadmedidaByUnidadMinimoCompra = tblunidadmedidaByUnidadMinimoCompra;
    }
    public String getCodigoArticulo() {
        return this.codigoArticulo;
    }
    
    public void setCodigoArticulo(String codigoArticulo) {
        this.codigoArticulo = codigoArticulo;
    }
    public String getNombreArticulo() {
        return this.nombreArticulo;
    }
    
    public void setNombreArticulo(String nombreArticulo) {
        this.nombreArticulo = nombreArticulo;
    }
    public String getPresentacion() {
        return this.presentacion;
    }
    
    public void setPresentacion(String presentacion) {
        this.presentacion = presentacion;
    }
    public double getCantidadMinimaUso() {
        return this.cantidadMinimaUso;
    }
    
    public void setCantidadMinimaUso(double cantidadMinimaUso) {
        this.cantidadMinimaUso = cantidadMinimaUso;
    }
    public double getCantidadMinimaCompra() {
        return this.cantidadMinimaCompra;
    }
    
    public void setCantidadMinimaCompra(double cantidadMinimaCompra) {
        this.cantidadMinimaCompra = cantidadMinimaCompra;
    }
    public double getExistencias() {
        return this.existencias;
    }
    
    public void setExistencias(double existencias) {
        this.existencias = existencias;
    }
    public boolean isPerecedero() {
        return this.perecedero;
    }
    
    public void setPerecedero(boolean perecedero) {
        this.perecedero = perecedero;
    }
    public double getFactorConversion() {
        return this.factorConversion;
    }
    
    public void setFactorConversion(double factorConversion) {
        this.factorConversion = factorConversion;
    }
    public String getRelacion() {
        return this.relacion;
    }
    
    public void setRelacion(String relacion) {
        this.relacion = relacion;
    }
    public boolean isUsoCompartido() {
        return this.usoCompartido;
    }
    
    public void setUsoCompartido(boolean usoCompartido) {
        this.usoCompartido = usoCompartido;
    }
    public Set getTbldetallepedidos() {
        return this.tbldetallepedidos;
    }
    
    public void setTbldetallepedidos(Set tbldetallepedidos) {
        this.tbldetallepedidos = tbldetallepedidos;
    }
    public Set getTblmovimientos() {
        return this.tblmovimientos;
    }
    
    public void setTblmovimientos(Set tblmovimientos) {
        this.tblmovimientos = tblmovimientos;
    }
    public Set getTblexamenarticulos() {
        return this.tblexamenarticulos;
    }
    
    public void setTblexamenarticulos(Set tblexamenarticulos) {
        this.tblexamenarticulos = tblexamenarticulos;
    }




}


