package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tblbitacora generated by hbm2java
 */
public class Tblbitacora  implements java.io.Serializable {


     private Long idBitacora;
     private Tblusuario tblusuario;
     private String tipoOperacion;
     private Date fecha;
     private Date hora;

    public Tblbitacora() {
    }

    public Tblbitacora(Tblusuario tblusuario, String tipoOperacion, Date fecha, Date hora) {
       this.tblusuario = tblusuario;
       this.tipoOperacion = tipoOperacion;
       this.fecha = fecha;
       this.hora = hora;
    }
   
    public Long getIdBitacora() {
        return this.idBitacora;
    }
    
    public void setIdBitacora(Long idBitacora) {
        this.idBitacora = idBitacora;
    }
    public Tblusuario getTblusuario() {
        return this.tblusuario;
    }
    
    public void setTblusuario(Tblusuario tblusuario) {
        this.tblusuario = tblusuario;
    }
    public String getTipoOperacion() {
        return this.tipoOperacion;
    }
    
    public void setTipoOperacion(String tipoOperacion) {
        this.tipoOperacion = tipoOperacion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }




}


