package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tblcargalaboral generated by hbm2java
 */
public class Tblcargalaboral  implements java.io.Serializable {


     private Long idCargaLaboral;
     private short horasAsignadas;
     private short mes;
     private short anio;
     private Set tblplanificaciontrabajos = new HashSet(0);

    public Tblcargalaboral() {
    }

	
    public Tblcargalaboral(short horasAsignadas, short mes, short anio) {
        this.horasAsignadas = horasAsignadas;
        this.mes = mes;
        this.anio = anio;
    }
    public Tblcargalaboral(short horasAsignadas, short mes, short anio, Set tblplanificaciontrabajos) {
       this.horasAsignadas = horasAsignadas;
       this.mes = mes;
       this.anio = anio;
       this.tblplanificaciontrabajos = tblplanificaciontrabajos;
    }
   
    public Long getIdCargaLaboral() {
        return this.idCargaLaboral;
    }
    
    public void setIdCargaLaboral(Long idCargaLaboral) {
        this.idCargaLaboral = idCargaLaboral;
    }
    public short getHorasAsignadas() {
        return this.horasAsignadas;
    }
    
    public void setHorasAsignadas(short horasAsignadas) {
        this.horasAsignadas = horasAsignadas;
    }
    public short getMes() {
        return this.mes;
    }
    
    public void setMes(short mes) {
        this.mes = mes;
    }
    public short getAnio() {
        return this.anio;
    }
    
    public void setAnio(short anio) {
        this.anio = anio;
    }
    public Set getTblplanificaciontrabajos() {
        return this.tblplanificaciontrabajos;
    }
    
    public void setTblplanificaciontrabajos(Set tblplanificaciontrabajos) {
        this.tblplanificaciontrabajos = tblplanificaciontrabajos;
    }




}


