package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA



/**
 * Tblcambioturno generated by hbm2java
 */
public class Tblcambioturno  implements java.io.Serializable {


     private Long idCambioTurno;
     private Tblplanificaciontrabajo tblplanificaciontrabajo;
     private Tblsolicitudcambioturno tblsolicitudcambioturno;
     private boolean solicitante;

    public Tblcambioturno() {
    }

    public Tblcambioturno(Tblplanificaciontrabajo tblplanificaciontrabajo, Tblsolicitudcambioturno tblsolicitudcambioturno, boolean solicitante) {
       this.tblplanificaciontrabajo = tblplanificaciontrabajo;
       this.tblsolicitudcambioturno = tblsolicitudcambioturno;
       this.solicitante = solicitante;
    }
   
    public Long getIdCambioTurno() {
        return this.idCambioTurno;
    }
    
    public void setIdCambioTurno(Long idCambioTurno) {
        this.idCambioTurno = idCambioTurno;
    }
    public Tblplanificaciontrabajo getTblplanificaciontrabajo() {
        return this.tblplanificaciontrabajo;
    }
    
    public void setTblplanificaciontrabajo(Tblplanificaciontrabajo tblplanificaciontrabajo) {
        this.tblplanificaciontrabajo = tblplanificaciontrabajo;
    }
    public Tblsolicitudcambioturno getTblsolicitudcambioturno() {
        return this.tblsolicitudcambioturno;
    }
    
    public void setTblsolicitudcambioturno(Tblsolicitudcambioturno tblsolicitudcambioturno) {
        this.tblsolicitudcambioturno = tblsolicitudcambioturno;
    }
    public boolean isSolicitante() {
        return this.solicitante;
    }
    
    public void setSolicitante(boolean solicitante) {
        this.solicitante = solicitante;
    }




}


