package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA



/**
 * Tblclinicaexterna generated by hbm2java
 */
public class Tblclinicaexterna  implements java.io.Serializable {


     private Short idClinicaExterna;
     private Tblservicio tblservicio;
     private String tipoClinica;
     private String nombreClinica;
     private String direccionClinica;
     private String telefonoClinica;
     private String encargado;

    public Tblclinicaexterna() {
    }

	
    public Tblclinicaexterna(Tblservicio tblservicio, String tipoClinica, String nombreClinica) {
        this.tblservicio = tblservicio;
        this.tipoClinica = tipoClinica;
        this.nombreClinica = nombreClinica;
    }
    public Tblclinicaexterna(Tblservicio tblservicio, String tipoClinica, String nombreClinica, String direccionClinica, String telefonoClinica, String encargado) {
       this.tblservicio = tblservicio;
       this.tipoClinica = tipoClinica;
       this.nombreClinica = nombreClinica;
       this.direccionClinica = direccionClinica;
       this.telefonoClinica = telefonoClinica;
       this.encargado = encargado;
    }
   
    public Short getIdClinicaExterna() {
        return this.idClinicaExterna;
    }
    
    public void setIdClinicaExterna(Short idClinicaExterna) {
        this.idClinicaExterna = idClinicaExterna;
    }
    public Tblservicio getTblservicio() {
        return this.tblservicio;
    }
    
    public void setTblservicio(Tblservicio tblservicio) {
        this.tblservicio = tblservicio;
    }
    public String getTipoClinica() {
        return this.tipoClinica;
    }
    
    public void setTipoClinica(String tipoClinica) {
        this.tipoClinica = tipoClinica;
    }
    public String getNombreClinica() {
        return this.nombreClinica;
    }
    
    public void setNombreClinica(String nombreClinica) {
        this.nombreClinica = nombreClinica;
    }
    public String getDireccionClinica() {
        return this.direccionClinica;
    }
    
    public void setDireccionClinica(String direccionClinica) {
        this.direccionClinica = direccionClinica;
    }
    public String getTelefonoClinica() {
        return this.telefonoClinica;
    }
    
    public void setTelefonoClinica(String telefonoClinica) {
        this.telefonoClinica = telefonoClinica;
    }
    public String getEncargado() {
        return this.encargado;
    }
    
    public void setEncargado(String encargado) {
        this.encargado = encargado;
    }




}


