package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tbldomicilio generated by hbm2java
 */
public class Tbldomicilio  implements java.io.Serializable {


     private Long idDomicilio;
     private Tblpersona tblpersona;
     private Tblmunicipio tblmunicipio;
     private String direccion;
     private String telefonoParticular;
     private Set tbltransfusions = new HashSet(0);
     private Set tblordens = new HashSet(0);

    public Tbldomicilio() {
    }

	
    public Tbldomicilio(Tblpersona tblpersona, Tblmunicipio tblmunicipio) {
        this.tblpersona = tblpersona;
        this.tblmunicipio = tblmunicipio;
    }
    public Tbldomicilio(Tblpersona tblpersona, Tblmunicipio tblmunicipio, String direccion, String telefonoParticular, Set tbltransfusions, Set tblordens) {
       this.tblpersona = tblpersona;
       this.tblmunicipio = tblmunicipio;
       this.direccion = direccion;
       this.telefonoParticular = telefonoParticular;
       this.tbltransfusions = tbltransfusions;
       this.tblordens = tblordens;
    }
   
    public Long getIdDomicilio() {
        return this.idDomicilio;
    }
    
    public void setIdDomicilio(Long idDomicilio) {
        this.idDomicilio = idDomicilio;
    }
    public Tblpersona getTblpersona() {
        return this.tblpersona;
    }
    
    public void setTblpersona(Tblpersona tblpersona) {
        this.tblpersona = tblpersona;
    }
    public Tblmunicipio getTblmunicipio() {
        return this.tblmunicipio;
    }
    
    public void setTblmunicipio(Tblmunicipio tblmunicipio) {
        this.tblmunicipio = tblmunicipio;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefonoParticular() {
        return this.telefonoParticular;
    }
    
    public void setTelefonoParticular(String telefonoParticular) {
        this.telefonoParticular = telefonoParticular;
    }
    public Set getTbltransfusions() {
        return this.tbltransfusions;
    }
    
    public void setTbltransfusions(Set tbltransfusions) {
        this.tbltransfusions = tbltransfusions;
    }
    public Set getTblordens() {
        return this.tblordens;
    }
    
    public void setTblordens(Set tblordens) {
        this.tblordens = tblordens;
    }




}


