package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA



/**
 * TbldetalleCuestionario generated by hbm2java
 */
public class TbldetalleCuestionario  implements java.io.Serializable {


     private Integer idDetalleCuestionario;
     private TblcuestionarioEvaluacion tblcuestionarioEvaluacion;
     private String detalle;

    public TbldetalleCuestionario() {
    }

    public TbldetalleCuestionario(TblcuestionarioEvaluacion tblcuestionarioEvaluacion, String detalle) {
       this.tblcuestionarioEvaluacion = tblcuestionarioEvaluacion;
       this.detalle = detalle;
    }
   
    public Integer getIdDetalleCuestionario() {
        return this.idDetalleCuestionario;
    }
    
    public void setIdDetalleCuestionario(Integer idDetalleCuestionario) {
        this.idDetalleCuestionario = idDetalleCuestionario;
    }
    public TblcuestionarioEvaluacion getTblcuestionarioEvaluacion() {
        return this.tblcuestionarioEvaluacion;
    }
    
    public void setTblcuestionarioEvaluacion(TblcuestionarioEvaluacion tblcuestionarioEvaluacion) {
        this.tblcuestionarioEvaluacion = tblcuestionarioEvaluacion;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }




}


