package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tbldepartamento generated by hbm2java
 */
public class Tbldepartamento  implements java.io.Serializable {


     private Short idDepartamento;
     private String nomDepartamento;
     private Set tblmunicipios = new HashSet(0);

    public Tbldepartamento() {
    }

	
    public Tbldepartamento(String nomDepartamento) {
        this.nomDepartamento = nomDepartamento;
    }
    public Tbldepartamento(String nomDepartamento, Set tblmunicipios) {
       this.nomDepartamento = nomDepartamento;
       this.tblmunicipios = tblmunicipios;
    }
   
    public Short getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(Short idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public String getNomDepartamento() {
        return this.nomDepartamento;
    }
    
    public void setNomDepartamento(String nomDepartamento) {
        this.nomDepartamento = nomDepartamento;
    }
    public Set getTblmunicipios() {
        return this.tblmunicipios;
    }
    
    public void setTblmunicipios(Set tblmunicipios) {
        this.tblmunicipios = tblmunicipios;
    }




}


