package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tbldonante generated by hbm2java
 */
public class Tbldonante  implements java.io.Serializable {


     private Long idDonate;
     private Tblpersona tblpersona;
     private boolean exclusionPermanente;
     private boolean exclusionDiferida;
     private Set tblevaluaciondonantes = new HashSet(0);
     private Set tblexcluidos = new HashSet(0);
     private Set tbltransfusions = new HashSet(0);

    public Tbldonante() {
    }

	
    public Tbldonante(Tblpersona tblpersona, boolean exclusionPermanente, boolean exclusionDiferida) {
        this.tblpersona = tblpersona;
        this.exclusionPermanente = exclusionPermanente;
        this.exclusionDiferida = exclusionDiferida;
    }
    public Tbldonante(Tblpersona tblpersona, boolean exclusionPermanente, boolean exclusionDiferida, Set tblevaluaciondonantes, Set tblexcluidos, Set tbltransfusions) {
       this.tblpersona = tblpersona;
       this.exclusionPermanente = exclusionPermanente;
       this.exclusionDiferida = exclusionDiferida;
       this.tblevaluaciondonantes = tblevaluaciondonantes;
       this.tblexcluidos = tblexcluidos;
       this.tbltransfusions = tbltransfusions;
    }
   
    public Long getIdDonate() {
        return this.idDonate;
    }
    
    public void setIdDonate(Long idDonate) {
        this.idDonate = idDonate;
    }
    public Tblpersona getTblpersona() {
        return this.tblpersona;
    }
    
    public void setTblpersona(Tblpersona tblpersona) {
        this.tblpersona = tblpersona;
    }
    public boolean isExclusionPermanente() {
        return this.exclusionPermanente;
    }
    
    public void setExclusionPermanente(boolean exclusionPermanente) {
        this.exclusionPermanente = exclusionPermanente;
    }
    public boolean isExclusionDiferida() {
        return this.exclusionDiferida;
    }
    
    public void setExclusionDiferida(boolean exclusionDiferida) {
        this.exclusionDiferida = exclusionDiferida;
    }
    public Set getTblevaluaciondonantes() {
        return this.tblevaluaciondonantes;
    }
    
    public void setTblevaluaciondonantes(Set tblevaluaciondonantes) {
        this.tblevaluaciondonantes = tblevaluaciondonantes;
    }
    public Set getTblexcluidos() {
        return this.tblexcluidos;
    }
    
    public void setTblexcluidos(Set tblexcluidos) {
        this.tblexcluidos = tblexcluidos;
    }
    public Set getTbltransfusions() {
        return this.tbltransfusions;
    }
    
    public void setTbltransfusions(Set tbltransfusions) {
        this.tbltransfusions = tbltransfusions;
    }




}


