package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA



/**
 * TblempleadoCapacitacion generated by hbm2java
 */
public class TblempleadoCapacitacion  implements java.io.Serializable {


     private TblempleadoCapacitacionId id;
     private Tblcapacitacioncontinua tblcapacitacioncontinua;
     private Tblempleado tblempleado;
     private String tipo;

    public TblempleadoCapacitacion() {
    }

    public TblempleadoCapacitacion(TblempleadoCapacitacionId id, Tblcapacitacioncontinua tblcapacitacioncontinua, Tblempleado tblempleado, String tipo) {
       this.id = id;
       this.tblcapacitacioncontinua = tblcapacitacioncontinua;
       this.tblempleado = tblempleado;
       this.tipo = tipo;
    }
   
    public TblempleadoCapacitacionId getId() {
        return this.id;
    }
    
    public void setId(TblempleadoCapacitacionId id) {
        this.id = id;
    }
    public Tblcapacitacioncontinua getTblcapacitacioncontinua() {
        return this.tblcapacitacioncontinua;
    }
    
    public void setTblcapacitacioncontinua(Tblcapacitacioncontinua tblcapacitacioncontinua) {
        this.tblcapacitacioncontinua = tblcapacitacioncontinua;
    }
    public Tblempleado getTblempleado() {
        return this.tblempleado;
    }
    
    public void setTblempleado(Tblempleado tblempleado) {
        this.tblempleado = tblempleado;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


