package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA



/**
 * Tblevaluacionfisica generated by hbm2java
 */
public class Tblevaluacionfisica  implements java.io.Serializable {


     private Long idEvaluacionFisica;
     private Tblevaluaciondonante tblevaluaciondonante;
     private double peso;
     private double presionArterial;
     private double pulso;
     private double temperatura;
     private Boolean hemograma;
     private Boolean hemoglobina;
     private double hematocrito;
     private String inspeccionBrazos;
     private Boolean tomoAlimentos;
     private String observaciones;

    public Tblevaluacionfisica() {
    }

	
    public Tblevaluacionfisica(Tblevaluaciondonante tblevaluaciondonante, double peso, double presionArterial, double pulso, double temperatura, double hematocrito, String inspeccionBrazos) {
        this.tblevaluaciondonante = tblevaluaciondonante;
        this.peso = peso;
        this.presionArterial = presionArterial;
        this.pulso = pulso;
        this.temperatura = temperatura;
        this.hematocrito = hematocrito;
        this.inspeccionBrazos = inspeccionBrazos;
    }
    public Tblevaluacionfisica(Tblevaluaciondonante tblevaluaciondonante, double peso, double presionArterial, double pulso, double temperatura, Boolean hemograma, Boolean hemoglobina, double hematocrito, String inspeccionBrazos, Boolean tomoAlimentos, String observaciones) {
       this.tblevaluaciondonante = tblevaluaciondonante;
       this.peso = peso;
       this.presionArterial = presionArterial;
       this.pulso = pulso;
       this.temperatura = temperatura;
       this.hemograma = hemograma;
       this.hemoglobina = hemoglobina;
       this.hematocrito = hematocrito;
       this.inspeccionBrazos = inspeccionBrazos;
       this.tomoAlimentos = tomoAlimentos;
       this.observaciones = observaciones;
    }
   
    public Long getIdEvaluacionFisica() {
        return this.idEvaluacionFisica;
    }
    
    public void setIdEvaluacionFisica(Long idEvaluacionFisica) {
        this.idEvaluacionFisica = idEvaluacionFisica;
    }
    public Tblevaluaciondonante getTblevaluaciondonante() {
        return this.tblevaluaciondonante;
    }
    
    public void setTblevaluaciondonante(Tblevaluaciondonante tblevaluaciondonante) {
        this.tblevaluaciondonante = tblevaluaciondonante;
    }
    public double getPeso() {
        return this.peso;
    }
    
    public void setPeso(double peso) {
        this.peso = peso;
    }
    public double getPresionArterial() {
        return this.presionArterial;
    }
    
    public void setPresionArterial(double presionArterial) {
        this.presionArterial = presionArterial;
    }
    public double getPulso() {
        return this.pulso;
    }
    
    public void setPulso(double pulso) {
        this.pulso = pulso;
    }
    public double getTemperatura() {
        return this.temperatura;
    }
    
    public void setTemperatura(double temperatura) {
        this.temperatura = temperatura;
    }
    public Boolean getHemograma() {
        return this.hemograma;
    }
    
    public void setHemograma(Boolean hemograma) {
        this.hemograma = hemograma;
    }
    public Boolean getHemoglobina() {
        return this.hemoglobina;
    }
    
    public void setHemoglobina(Boolean hemoglobina) {
        this.hemoglobina = hemoglobina;
    }
    public double getHematocrito() {
        return this.hematocrito;
    }
    
    public void setHematocrito(double hematocrito) {
        this.hematocrito = hematocrito;
    }
    public String getInspeccionBrazos() {
        return this.inspeccionBrazos;
    }
    
    public void setInspeccionBrazos(String inspeccionBrazos) {
        this.inspeccionBrazos = inspeccionBrazos;
    }
    public Boolean getTomoAlimentos() {
        return this.tomoAlimentos;
    }
    
    public void setTomoAlimentos(Boolean tomoAlimentos) {
        this.tomoAlimentos = tomoAlimentos;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


