package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tblexamen generated by hbm2java
 */
public class Tblexamen  implements java.io.Serializable {


     private Long idExamen;
     private Tblseccion tblseccion;
     private String codigoExamen;
     private String nombreExamen;
     private Set tblexamenOrdens = new HashSet(0);
     private Set tblparametros = new HashSet(0);
     private Set tblexamenarticulos = new HashSet(0);

    public Tblexamen() {
    }

	
    public Tblexamen(Tblseccion tblseccion, String codigoExamen, String nombreExamen) {
        this.tblseccion = tblseccion;
        this.codigoExamen = codigoExamen;
        this.nombreExamen = nombreExamen;
    }
    public Tblexamen(Tblseccion tblseccion, String codigoExamen, String nombreExamen, Set tblexamenOrdens, Set tblparametros, Set tblexamenarticulos) {
       this.tblseccion = tblseccion;
       this.codigoExamen = codigoExamen;
       this.nombreExamen = nombreExamen;
       this.tblexamenOrdens = tblexamenOrdens;
       this.tblparametros = tblparametros;
       this.tblexamenarticulos = tblexamenarticulos;
    }
   
    public Long getIdExamen() {
        return this.idExamen;
    }
    
    public void setIdExamen(Long idExamen) {
        this.idExamen = idExamen;
    }
    public Tblseccion getTblseccion() {
        return this.tblseccion;
    }
    
    public void setTblseccion(Tblseccion tblseccion) {
        this.tblseccion = tblseccion;
    }
    public String getCodigoExamen() {
        return this.codigoExamen;
    }
    
    public void setCodigoExamen(String codigoExamen) {
        this.codigoExamen = codigoExamen;
    }
    public String getNombreExamen() {
        return this.nombreExamen;
    }
    
    public void setNombreExamen(String nombreExamen) {
        this.nombreExamen = nombreExamen;
    }
    public Set getTblexamenOrdens() {
        return this.tblexamenOrdens;
    }
    
    public void setTblexamenOrdens(Set tblexamenOrdens) {
        this.tblexamenOrdens = tblexamenOrdens;
    }
    public Set getTblparametros() {
        return this.tblparametros;
    }
    
    public void setTblparametros(Set tblparametros) {
        this.tblparametros = tblparametros;
    }
    public Set getTblexamenarticulos() {
        return this.tblexamenarticulos;
    }
    
    public void setTblexamenarticulos(Set tblexamenarticulos) {
        this.tblexamenarticulos = tblexamenarticulos;
    }




}


