package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblentrada generated by hbm2java
 */
public class Tblentrada  implements java.io.Serializable {


     private Long idEntrada;
     private Tblprocedenciaarticulo tblprocedenciaarticulo;
     private Tblmovimiento tblmovimiento;
     private int numeroVale;
     private Integer numeroLote;
     private Date fechaVencimiento;
     private double cantidad;
     private double precio;
     private Date fechaRecepcion;
     private double existencia;
     private Date vencimientoMaximo;
     private Set tblsalidas = new HashSet(0);

    public Tblentrada() {
    }

	
    public Tblentrada(Tblprocedenciaarticulo tblprocedenciaarticulo, Tblmovimiento tblmovimiento, int numeroVale, double cantidad, double precio, Date fechaRecepcion, double existencia) {
        this.tblprocedenciaarticulo = tblprocedenciaarticulo;
        this.tblmovimiento = tblmovimiento;
        this.numeroVale = numeroVale;
        this.cantidad = cantidad;
        this.precio = precio;
        this.fechaRecepcion = fechaRecepcion;
        this.existencia = existencia;
    }
    public Tblentrada(Tblprocedenciaarticulo tblprocedenciaarticulo, Tblmovimiento tblmovimiento, int numeroVale, Integer numeroLote, Date fechaVencimiento, double cantidad, double precio, Date fechaRecepcion, double existencia, Date vencimientoMaximo, Set tblsalidas) {
       this.tblprocedenciaarticulo = tblprocedenciaarticulo;
       this.tblmovimiento = tblmovimiento;
       this.numeroVale = numeroVale;
       this.numeroLote = numeroLote;
       this.fechaVencimiento = fechaVencimiento;
       this.cantidad = cantidad;
       this.precio = precio;
       this.fechaRecepcion = fechaRecepcion;
       this.existencia = existencia;
       this.vencimientoMaximo = vencimientoMaximo;
       this.tblsalidas = tblsalidas;
    }
   
    public Long getIdEntrada() {
        return this.idEntrada;
    }
    
    public void setIdEntrada(Long idEntrada) {
        this.idEntrada = idEntrada;
    }
    public Tblprocedenciaarticulo getTblprocedenciaarticulo() {
        return this.tblprocedenciaarticulo;
    }
    
    public void setTblprocedenciaarticulo(Tblprocedenciaarticulo tblprocedenciaarticulo) {
        this.tblprocedenciaarticulo = tblprocedenciaarticulo;
    }
    public Tblmovimiento getTblmovimiento() {
        return this.tblmovimiento;
    }
    
    public void setTblmovimiento(Tblmovimiento tblmovimiento) {
        this.tblmovimiento = tblmovimiento;
    }
    public int getNumeroVale() {
        return this.numeroVale;
    }
    
    public void setNumeroVale(int numeroVale) {
        this.numeroVale = numeroVale;
    }
    public Integer getNumeroLote() {
        return this.numeroLote;
    }
    
    public void setNumeroLote(Integer numeroLote) {
        this.numeroLote = numeroLote;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public Date getFechaRecepcion() {
        return this.fechaRecepcion;
    }
    
    public void setFechaRecepcion(Date fechaRecepcion) {
        this.fechaRecepcion = fechaRecepcion;
    }
    public double getExistencia() {
        return this.existencia;
    }
    
    public void setExistencia(double existencia) {
        this.existencia = existencia;
    }
    public Date getVencimientoMaximo() {
        return this.vencimientoMaximo;
    }
    
    public void setVencimientoMaximo(Date vencimientoMaximo) {
        this.vencimientoMaximo = vencimientoMaximo;
    }
    public Set getTblsalidas() {
        return this.tblsalidas;
    }
    
    public void setTblsalidas(Set tblsalidas) {
        this.tblsalidas = tblsalidas;
    }




}


