package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA



/**
 * TblempleadoCapacitacionId generated by hbm2java
 */
public class TblempleadoCapacitacionId  implements java.io.Serializable {


     private short codigoMarcacion;
     private long idCapacitacion;

    public TblempleadoCapacitacionId() {
    }

    public TblempleadoCapacitacionId(short codigoMarcacion, long idCapacitacion) {
       this.codigoMarcacion = codigoMarcacion;
       this.idCapacitacion = idCapacitacion;
    }
   
    public short getCodigoMarcacion() {
        return this.codigoMarcacion;
    }
    
    public void setCodigoMarcacion(short codigoMarcacion) {
        this.codigoMarcacion = codigoMarcacion;
    }
    public long getIdCapacitacion() {
        return this.idCapacitacion;
    }
    
    public void setIdCapacitacion(long idCapacitacion) {
        this.idCapacitacion = idCapacitacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblempleadoCapacitacionId) ) return false;
		 TblempleadoCapacitacionId castOther = ( TblempleadoCapacitacionId ) other; 
         
		 return (this.getCodigoMarcacion()==castOther.getCodigoMarcacion())
 && (this.getIdCapacitacion()==castOther.getIdCapacitacion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodigoMarcacion();
         result = 37 * result + (int) this.getIdCapacitacion();
         return result;
   }   


}


