package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tblexcluido generated by hbm2java
 */
public class Tblexcluido  implements java.io.Serializable {


     private Long idDonanteExcluido;
     private Tbldonante tbldonante;
     private String catExclusion;
     private String lugExclusion;
     private Date fecExclusion;
     private int tiempoExclusion;
     private Date fecElegibilidad;
     private String motivoExclusion;
     private String periodoExclusion;

    public Tblexcluido() {
    }

	
    public Tblexcluido(Tbldonante tbldonante, String catExclusion, String lugExclusion, Date fecExclusion, int tiempoExclusion, Date fecElegibilidad) {
        this.tbldonante = tbldonante;
        this.catExclusion = catExclusion;
        this.lugExclusion = lugExclusion;
        this.fecExclusion = fecExclusion;
        this.tiempoExclusion = tiempoExclusion;
        this.fecElegibilidad = fecElegibilidad;
    }
    public Tblexcluido(Tbldonante tbldonante, String catExclusion, String lugExclusion, Date fecExclusion, int tiempoExclusion, Date fecElegibilidad, String motivoExclusion, String periodoExclusion) {
       this.tbldonante = tbldonante;
       this.catExclusion = catExclusion;
       this.lugExclusion = lugExclusion;
       this.fecExclusion = fecExclusion;
       this.tiempoExclusion = tiempoExclusion;
       this.fecElegibilidad = fecElegibilidad;
       this.motivoExclusion = motivoExclusion;
       this.periodoExclusion = periodoExclusion;
    }
   
    public Long getIdDonanteExcluido() {
        return this.idDonanteExcluido;
    }
    
    public void setIdDonanteExcluido(Long idDonanteExcluido) {
        this.idDonanteExcluido = idDonanteExcluido;
    }
    public Tbldonante getTbldonante() {
        return this.tbldonante;
    }
    
    public void setTbldonante(Tbldonante tbldonante) {
        this.tbldonante = tbldonante;
    }
    public String getCatExclusion() {
        return this.catExclusion;
    }
    
    public void setCatExclusion(String catExclusion) {
        this.catExclusion = catExclusion;
    }
    public String getLugExclusion() {
        return this.lugExclusion;
    }
    
    public void setLugExclusion(String lugExclusion) {
        this.lugExclusion = lugExclusion;
    }
    public Date getFecExclusion() {
        return this.fecExclusion;
    }
    
    public void setFecExclusion(Date fecExclusion) {
        this.fecExclusion = fecExclusion;
    }
    public int getTiempoExclusion() {
        return this.tiempoExclusion;
    }
    
    public void setTiempoExclusion(int tiempoExclusion) {
        this.tiempoExclusion = tiempoExclusion;
    }
    public Date getFecElegibilidad() {
        return this.fecElegibilidad;
    }
    
    public void setFecElegibilidad(Date fecElegibilidad) {
        this.fecElegibilidad = fecElegibilidad;
    }
    public String getMotivoExclusion() {
        return this.motivoExclusion;
    }
    
    public void setMotivoExclusion(String motivoExclusion) {
        this.motivoExclusion = motivoExclusion;
    }
    public String getPeriodoExclusion() {
        return this.periodoExclusion;
    }
    
    public void setPeriodoExclusion(String periodoExclusion) {
        this.periodoExclusion = periodoExclusion;
    }




}


