package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tblestablecimiento generated by hbm2java
 */
public class Tblestablecimiento  implements java.io.Serializable {


     private int idEstablecimiento;
     private Tblmunicipio tblmunicipio;
     private String nombre;
     private String codigo;
     private String direccion;
     private String telefono;
     private String tema;
     private Byte logo;
     private String obejtivoGeneral;
     private String objetivos;
     private String metas;
     private String politicas;
     private Set tbljefes = new HashSet(0);
     private Set tbldirectors = new HashSet(0);

    public Tblestablecimiento() {
    }

	
    public Tblestablecimiento(int idEstablecimiento, Tblmunicipio tblmunicipio, String nombre, String codigo, String direccion, String telefono) {
        this.idEstablecimiento = idEstablecimiento;
        this.tblmunicipio = tblmunicipio;
        this.nombre = nombre;
        this.codigo = codigo;
        this.direccion = direccion;
        this.telefono = telefono;
    }
    public Tblestablecimiento(int idEstablecimiento, Tblmunicipio tblmunicipio, String nombre, String codigo, String direccion, String telefono, String tema, Byte logo, String obejtivoGeneral, String objetivos, String metas, String politicas, Set tbljefes, Set tbldirectors) {
       this.idEstablecimiento = idEstablecimiento;
       this.tblmunicipio = tblmunicipio;
       this.nombre = nombre;
       this.codigo = codigo;
       this.direccion = direccion;
       this.telefono = telefono;
       this.tema = tema;
       this.logo = logo;
       this.obejtivoGeneral = obejtivoGeneral;
       this.objetivos = objetivos;
       this.metas = metas;
       this.politicas = politicas;
       this.tbljefes = tbljefes;
       this.tbldirectors = tbldirectors;
    }
   
    public int getIdEstablecimiento() {
        return this.idEstablecimiento;
    }
    
    public void setIdEstablecimiento(int idEstablecimiento) {
        this.idEstablecimiento = idEstablecimiento;
    }
    public Tblmunicipio getTblmunicipio() {
        return this.tblmunicipio;
    }
    
    public void setTblmunicipio(Tblmunicipio tblmunicipio) {
        this.tblmunicipio = tblmunicipio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getTema() {
        return this.tema;
    }
    
    public void setTema(String tema) {
        this.tema = tema;
    }
    public Byte getLogo() {
        return this.logo;
    }
    
    public void setLogo(Byte logo) {
        this.logo = logo;
    }
    public String getObejtivoGeneral() {
        return this.obejtivoGeneral;
    }
    
    public void setObejtivoGeneral(String obejtivoGeneral) {
        this.obejtivoGeneral = obejtivoGeneral;
    }
    public String getObjetivos() {
        return this.objetivos;
    }
    
    public void setObjetivos(String objetivos) {
        this.objetivos = objetivos;
    }
    public String getMetas() {
        return this.metas;
    }
    
    public void setMetas(String metas) {
        this.metas = metas;
    }
    public String getPoliticas() {
        return this.politicas;
    }
    
    public void setPoliticas(String politicas) {
        this.politicas = politicas;
    }
    public Set getTbljefes() {
        return this.tbljefes;
    }
    
    public void setTbljefes(Set tbljefes) {
        this.tbljefes = tbljefes;
    }
    public Set getTbldirectors() {
        return this.tbldirectors;
    }
    
    public void setTbldirectors(Set tbldirectors) {
        this.tbldirectors = tbldirectors;
    }




}


