package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tblentregaresultado generated by hbm2java
 */
public class Tblentregaresultado  implements java.io.Serializable {


     private Long idEntregaResultado;
     private Tblpersona tblpersona;
     private TblexamenOrden tblexamenOrden;
     private Date fechaEntrega;

    public Tblentregaresultado() {
    }

    public Tblentregaresultado(Tblpersona tblpersona, TblexamenOrden tblexamenOrden, Date fechaEntrega) {
       this.tblpersona = tblpersona;
       this.tblexamenOrden = tblexamenOrden;
       this.fechaEntrega = fechaEntrega;
    }
   
    public Long getIdEntregaResultado() {
        return this.idEntregaResultado;
    }
    
    public void setIdEntregaResultado(Long idEntregaResultado) {
        this.idEntregaResultado = idEntregaResultado;
    }
    public Tblpersona getTblpersona() {
        return this.tblpersona;
    }
    
    public void setTblpersona(Tblpersona tblpersona) {
        this.tblpersona = tblpersona;
    }
    public TblexamenOrden getTblexamenOrden() {
        return this.tblexamenOrden;
    }
    
    public void setTblexamenOrden(TblexamenOrden tblexamenOrden) {
        this.tblexamenOrden = tblexamenOrden;
    }
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }




}


