package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblincidencia generated by hbm2java
 */
public class Tblincidencia  implements java.io.Serializable {


     private Long idIncidencia;
     private Date fecha;
     private String motivo;
     private String descripcion;
     private Set tblresultados = new HashSet(0);
     private Set tblexamenOrdens = new HashSet(0);

    public Tblincidencia() {
    }

	
    public Tblincidencia(Date fecha, String motivo) {
        this.fecha = fecha;
        this.motivo = motivo;
    }
    public Tblincidencia(Date fecha, String motivo, String descripcion, Set tblresultados, Set tblexamenOrdens) {
       this.fecha = fecha;
       this.motivo = motivo;
       this.descripcion = descripcion;
       this.tblresultados = tblresultados;
       this.tblexamenOrdens = tblexamenOrdens;
    }
   
    public Long getIdIncidencia() {
        return this.idIncidencia;
    }
    
    public void setIdIncidencia(Long idIncidencia) {
        this.idIncidencia = idIncidencia;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getTblresultados() {
        return this.tblresultados;
    }
    
    public void setTblresultados(Set tblresultados) {
        this.tblresultados = tblresultados;
    }
    public Set getTblexamenOrdens() {
        return this.tblexamenOrdens;
    }
    
    public void setTblexamenOrdens(Set tblexamenOrdens) {
        this.tblexamenOrdens = tblexamenOrdens;
    }




}


