package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tblinstitucion generated by hbm2java
 */
public class Tblinstitucion  implements java.io.Serializable {


     private Short idInstitucion;
     private String nombre;
     private String telefono;
     private String direccion;
     private Set tblcapacitacioncontinuas = new HashSet(0);

    public Tblinstitucion() {
    }

	
    public Tblinstitucion(String nombre) {
        this.nombre = nombre;
    }
    public Tblinstitucion(String nombre, String telefono, String direccion, Set tblcapacitacioncontinuas) {
       this.nombre = nombre;
       this.telefono = telefono;
       this.direccion = direccion;
       this.tblcapacitacioncontinuas = tblcapacitacioncontinuas;
    }
   
    public Short getIdInstitucion() {
        return this.idInstitucion;
    }
    
    public void setIdInstitucion(Short idInstitucion) {
        this.idInstitucion = idInstitucion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getTblcapacitacioncontinuas() {
        return this.tblcapacitacioncontinuas;
    }
    
    public void setTblcapacitacioncontinuas(Set tblcapacitacioncontinuas) {
        this.tblcapacitacioncontinuas = tblcapacitacioncontinuas;
    }




}


