package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA



/**
 * Tbllaboratorio generated by hbm2java
 */
public class Tbllaboratorio  implements java.io.Serializable {


     private Short idLaboratorio;
     private String nombreLaboratorio;
     private String telefono;

    public Tbllaboratorio() {
    }

	
    public Tbllaboratorio(String nombreLaboratorio) {
        this.nombreLaboratorio = nombreLaboratorio;
    }
    public Tbllaboratorio(String nombreLaboratorio, String telefono) {
       this.nombreLaboratorio = nombreLaboratorio;
       this.telefono = telefono;
    }
   
    public Short getIdLaboratorio() {
        return this.idLaboratorio;
    }
    
    public void setIdLaboratorio(Short idLaboratorio) {
        this.idLaboratorio = idLaboratorio;
    }
    public String getNombreLaboratorio() {
        return this.nombreLaboratorio;
    }
    
    public void setNombreLaboratorio(String nombreLaboratorio) {
        this.nombreLaboratorio = nombreLaboratorio;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


