package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tbllugtrabajo generated by hbm2java
 */
public class Tbllugtrabajo  implements java.io.Serializable {


     private Long idLugarTrabajo;
     private Tblpersona tblpersona;
     private String lugarTrabajo;
     private String direccionTrabajo;
     private String telefonoTrabajo;
     private Set tblordens = new HashSet(0);
     private Set tbltransfusions = new HashSet(0);

    public Tbllugtrabajo() {
    }

	
    public Tbllugtrabajo(Tblpersona tblpersona, String lugarTrabajo) {
        this.tblpersona = tblpersona;
        this.lugarTrabajo = lugarTrabajo;
    }
    public Tbllugtrabajo(Tblpersona tblpersona, String lugarTrabajo, String direccionTrabajo, String telefonoTrabajo, Set tblordens, Set tbltransfusions) {
       this.tblpersona = tblpersona;
       this.lugarTrabajo = lugarTrabajo;
       this.direccionTrabajo = direccionTrabajo;
       this.telefonoTrabajo = telefonoTrabajo;
       this.tblordens = tblordens;
       this.tbltransfusions = tbltransfusions;
    }
   
    public Long getIdLugarTrabajo() {
        return this.idLugarTrabajo;
    }
    
    public void setIdLugarTrabajo(Long idLugarTrabajo) {
        this.idLugarTrabajo = idLugarTrabajo;
    }
    public Tblpersona getTblpersona() {
        return this.tblpersona;
    }
    
    public void setTblpersona(Tblpersona tblpersona) {
        this.tblpersona = tblpersona;
    }
    public String getLugarTrabajo() {
        return this.lugarTrabajo;
    }
    
    public void setLugarTrabajo(String lugarTrabajo) {
        this.lugarTrabajo = lugarTrabajo;
    }
    public String getDireccionTrabajo() {
        return this.direccionTrabajo;
    }
    
    public void setDireccionTrabajo(String direccionTrabajo) {
        this.direccionTrabajo = direccionTrabajo;
    }
    public String getTelefonoTrabajo() {
        return this.telefonoTrabajo;
    }
    
    public void setTelefonoTrabajo(String telefonoTrabajo) {
        this.telefonoTrabajo = telefonoTrabajo;
    }
    public Set getTblordens() {
        return this.tblordens;
    }
    
    public void setTblordens(Set tblordens) {
        this.tblordens = tblordens;
    }
    public Set getTbltransfusions() {
        return this.tbltransfusions;
    }
    
    public void setTbltransfusions(Set tbltransfusions) {
        this.tbltransfusions = tbltransfusions;
    }




}


