package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tblmunicipio generated by hbm2java
 */
public class Tblmunicipio  implements java.io.Serializable {


     private Short idMunicipio;
     private Tbldepartamento tbldepartamento;
     private String nomMunicipio;
     private Set tblestablecimientos = new HashSet(0);
     private Set tbldomicilios = new HashSet(0);

    public Tblmunicipio() {
    }

	
    public Tblmunicipio(Tbldepartamento tbldepartamento, String nomMunicipio) {
        this.tbldepartamento = tbldepartamento;
        this.nomMunicipio = nomMunicipio;
    }
    public Tblmunicipio(Tbldepartamento tbldepartamento, String nomMunicipio, Set tblestablecimientos, Set tbldomicilios) {
       this.tbldepartamento = tbldepartamento;
       this.nomMunicipio = nomMunicipio;
       this.tblestablecimientos = tblestablecimientos;
       this.tbldomicilios = tbldomicilios;
    }
   
    public Short getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(Short idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public Tbldepartamento getTbldepartamento() {
        return this.tbldepartamento;
    }
    
    public void setTbldepartamento(Tbldepartamento tbldepartamento) {
        this.tbldepartamento = tbldepartamento;
    }
    public String getNomMunicipio() {
        return this.nomMunicipio;
    }
    
    public void setNomMunicipio(String nomMunicipio) {
        this.nomMunicipio = nomMunicipio;
    }
    public Set getTblestablecimientos() {
        return this.tblestablecimientos;
    }
    
    public void setTblestablecimientos(Set tblestablecimientos) {
        this.tblestablecimientos = tblestablecimientos;
    }
    public Set getTbldomicilios() {
        return this.tbldomicilios;
    }
    
    public void setTbldomicilios(Set tbldomicilios) {
        this.tbldomicilios = tbldomicilios;
    }




}


