package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tblmedico generated by hbm2java
 */
public class Tblmedico  implements java.io.Serializable {


     private Integer idMedico;
     private Tblpersona tblpersona;
     private String codMedico;
     private Set tblordens = new HashSet(0);

    public Tblmedico() {
    }

	
    public Tblmedico(Tblpersona tblpersona, String codMedico) {
        this.tblpersona = tblpersona;
        this.codMedico = codMedico;
    }
    public Tblmedico(Tblpersona tblpersona, String codMedico, Set tblordens) {
       this.tblpersona = tblpersona;
       this.codMedico = codMedico;
       this.tblordens = tblordens;
    }
   
    public Integer getIdMedico() {
        return this.idMedico;
    }
    
    public void setIdMedico(Integer idMedico) {
        this.idMedico = idMedico;
    }
    public Tblpersona getTblpersona() {
        return this.tblpersona;
    }
    
    public void setTblpersona(Tblpersona tblpersona) {
        this.tblpersona = tblpersona;
    }
    public String getCodMedico() {
        return this.codMedico;
    }
    
    public void setCodMedico(String codMedico) {
        this.codMedico = codMedico;
    }
    public Set getTblordens() {
        return this.tblordens;
    }
    
    public void setTblordens(Set tblordens) {
        this.tblordens = tblordens;
    }




}


