package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblmovimiento generated by hbm2java
 */
public class Tblmovimiento  implements java.io.Serializable {


     private Long idMovimiento;
     private Tblarticulo tblarticulo;
     private boolean tipoMovimiento;
     private Date fecha;
     private String concepto;
     private Set tblentradas = new HashSet(0);
     private Set tblsalidas = new HashSet(0);

    public Tblmovimiento() {
    }

	
    public Tblmovimiento(Tblarticulo tblarticulo, boolean tipoMovimiento, Date fecha) {
        this.tblarticulo = tblarticulo;
        this.tipoMovimiento = tipoMovimiento;
        this.fecha = fecha;
    }
    public Tblmovimiento(Tblarticulo tblarticulo, boolean tipoMovimiento, Date fecha, String concepto, Set tblentradas, Set tblsalidas) {
       this.tblarticulo = tblarticulo;
       this.tipoMovimiento = tipoMovimiento;
       this.fecha = fecha;
       this.concepto = concepto;
       this.tblentradas = tblentradas;
       this.tblsalidas = tblsalidas;
    }
   
    public Long getIdMovimiento() {
        return this.idMovimiento;
    }
    
    public void setIdMovimiento(Long idMovimiento) {
        this.idMovimiento = idMovimiento;
    }
    public Tblarticulo getTblarticulo() {
        return this.tblarticulo;
    }
    
    public void setTblarticulo(Tblarticulo tblarticulo) {
        this.tblarticulo = tblarticulo;
    }
    public boolean isTipoMovimiento() {
        return this.tipoMovimiento;
    }
    
    public void setTipoMovimiento(boolean tipoMovimiento) {
        this.tipoMovimiento = tipoMovimiento;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public Set getTblentradas() {
        return this.tblentradas;
    }
    
    public void setTblentradas(Set tblentradas) {
        this.tblentradas = tblentradas;
    }
    public Set getTblsalidas() {
        return this.tblsalidas;
    }
    
    public void setTblsalidas(Set tblsalidas) {
        this.tblsalidas = tblsalidas;
    }




}


