package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblorden generated by hbm2java
 */
public class Tblorden  implements java.io.Serializable {


     private Long idOrden;
     private Tblempleado tblempleado;
     private Tblservicio tblservicio;
     private Tblpaciente tblpaciente;
     private Tblmedico tblmedico;
     private Tblespecialidad tblespecialidad;
     private Date fechaRecepcion;
     private String observacionesRecepcion;
     private String observaiconesResultados;
     private Integer numeroCama;
     private Set tblsolicitudvihs = new HashSet(0);
     private Set tbldomicilios = new HashSet(0);
     private Set tblexamenOrdens = new HashSet(0);
     private Set tbllugtrabajos = new HashSet(0);

    public Tblorden() {
    }

	
    public Tblorden(Tblempleado tblempleado, Tblservicio tblservicio, Tblpaciente tblpaciente, Tblmedico tblmedico, Tblespecialidad tblespecialidad, Date fechaRecepcion) {
        this.tblempleado = tblempleado;
        this.tblservicio = tblservicio;
        this.tblpaciente = tblpaciente;
        this.tblmedico = tblmedico;
        this.tblespecialidad = tblespecialidad;
        this.fechaRecepcion = fechaRecepcion;
    }
    public Tblorden(Tblempleado tblempleado, Tblservicio tblservicio, Tblpaciente tblpaciente, Tblmedico tblmedico, Tblespecialidad tblespecialidad, Date fechaRecepcion, String observacionesRecepcion, String observaiconesResultados, Integer numeroCama, Set tblsolicitudvihs, Set tbldomicilios, Set tblexamenOrdens, Set tbllugtrabajos) {
       this.tblempleado = tblempleado;
       this.tblservicio = tblservicio;
       this.tblpaciente = tblpaciente;
       this.tblmedico = tblmedico;
       this.tblespecialidad = tblespecialidad;
       this.fechaRecepcion = fechaRecepcion;
       this.observacionesRecepcion = observacionesRecepcion;
       this.observaiconesResultados = observaiconesResultados;
       this.numeroCama = numeroCama;
       this.tblsolicitudvihs = tblsolicitudvihs;
       this.tbldomicilios = tbldomicilios;
       this.tblexamenOrdens = tblexamenOrdens;
       this.tbllugtrabajos = tbllugtrabajos;
    }
   
    public Long getIdOrden() {
        return this.idOrden;
    }
    
    public void setIdOrden(Long idOrden) {
        this.idOrden = idOrden;
    }
    public Tblempleado getTblempleado() {
        return this.tblempleado;
    }
    
    public void setTblempleado(Tblempleado tblempleado) {
        this.tblempleado = tblempleado;
    }
    public Tblservicio getTblservicio() {
        return this.tblservicio;
    }
    
    public void setTblservicio(Tblservicio tblservicio) {
        this.tblservicio = tblservicio;
    }
    public Tblpaciente getTblpaciente() {
        return this.tblpaciente;
    }
    
    public void setTblpaciente(Tblpaciente tblpaciente) {
        this.tblpaciente = tblpaciente;
    }
    public Tblmedico getTblmedico() {
        return this.tblmedico;
    }
    
    public void setTblmedico(Tblmedico tblmedico) {
        this.tblmedico = tblmedico;
    }
    public Tblespecialidad getTblespecialidad() {
        return this.tblespecialidad;
    }
    
    public void setTblespecialidad(Tblespecialidad tblespecialidad) {
        this.tblespecialidad = tblespecialidad;
    }
    public Date getFechaRecepcion() {
        return this.fechaRecepcion;
    }
    
    public void setFechaRecepcion(Date fechaRecepcion) {
        this.fechaRecepcion = fechaRecepcion;
    }
    public String getObservacionesRecepcion() {
        return this.observacionesRecepcion;
    }
    
    public void setObservacionesRecepcion(String observacionesRecepcion) {
        this.observacionesRecepcion = observacionesRecepcion;
    }
    public String getObservaiconesResultados() {
        return this.observaiconesResultados;
    }
    
    public void setObservaiconesResultados(String observaiconesResultados) {
        this.observaiconesResultados = observaiconesResultados;
    }
    public Integer getNumeroCama() {
        return this.numeroCama;
    }
    
    public void setNumeroCama(Integer numeroCama) {
        this.numeroCama = numeroCama;
    }
    public Set getTblsolicitudvihs() {
        return this.tblsolicitudvihs;
    }
    
    public void setTblsolicitudvihs(Set tblsolicitudvihs) {
        this.tblsolicitudvihs = tblsolicitudvihs;
    }
    public Set getTbldomicilios() {
        return this.tbldomicilios;
    }
    
    public void setTbldomicilios(Set tbldomicilios) {
        this.tbldomicilios = tbldomicilios;
    }
    public Set getTblexamenOrdens() {
        return this.tblexamenOrdens;
    }
    
    public void setTblexamenOrdens(Set tblexamenOrdens) {
        this.tblexamenOrdens = tblexamenOrdens;
    }
    public Set getTbllugtrabajos() {
        return this.tbllugtrabajos;
    }
    
    public void setTbllugtrabajos(Set tbllugtrabajos) {
        this.tbllugtrabajos = tbllugtrabajos;
    }




}


