package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tblobjeto generated by hbm2java
 */
public class Tblobjeto  implements java.io.Serializable {


     private Short idObjeto;
     private Tblobjeto tblobjeto;
     private String tipoObjeto;
     private String nombreObjeto;
     private String grupo;
     private Set tblpaginas = new HashSet(0);
     private Set tblprivilegios = new HashSet(0);
     private Set tblobjetos = new HashSet(0);

    public Tblobjeto() {
    }

	
    public Tblobjeto(String tipoObjeto, String nombreObjeto) {
        this.tipoObjeto = tipoObjeto;
        this.nombreObjeto = nombreObjeto;
    }
    public Tblobjeto(Tblobjeto tblobjeto, String tipoObjeto, String nombreObjeto, String grupo, Set tblpaginas, Set tblprivilegios, Set tblobjetos) {
       this.tblobjeto = tblobjeto;
       this.tipoObjeto = tipoObjeto;
       this.nombreObjeto = nombreObjeto;
       this.grupo = grupo;
       this.tblpaginas = tblpaginas;
       this.tblprivilegios = tblprivilegios;
       this.tblobjetos = tblobjetos;
    }
   
    public Short getIdObjeto() {
        return this.idObjeto;
    }
    
    public void setIdObjeto(Short idObjeto) {
        this.idObjeto = idObjeto;
    }
    public Tblobjeto getTblobjeto() {
        return this.tblobjeto;
    }
    
    public void setTblobjeto(Tblobjeto tblobjeto) {
        this.tblobjeto = tblobjeto;
    }
    public String getTipoObjeto() {
        return this.tipoObjeto;
    }
    
    public void setTipoObjeto(String tipoObjeto) {
        this.tipoObjeto = tipoObjeto;
    }
    public String getNombreObjeto() {
        return this.nombreObjeto;
    }
    
    public void setNombreObjeto(String nombreObjeto) {
        this.nombreObjeto = nombreObjeto;
    }
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    public Set getTblpaginas() {
        return this.tblpaginas;
    }
    
    public void setTblpaginas(Set tblpaginas) {
        this.tblpaginas = tblpaginas;
    }
    public Set getTblprivilegios() {
        return this.tblprivilegios;
    }
    
    public void setTblprivilegios(Set tblprivilegios) {
        this.tblprivilegios = tblprivilegios;
    }
    public Set getTblobjetos() {
        return this.tblobjetos;
    }
    
    public void setTblobjetos(Set tblobjetos) {
        this.tblobjetos = tblobjetos;
    }




}


