package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA



/**
 * Tblprivilegio generated by hbm2java
 */
public class Tblprivilegio  implements java.io.Serializable {


     private Short idPrivilegio;
     private Tblrol tblrol;
     private Tblobjeto tblobjeto;
     private boolean permiso;

    public Tblprivilegio() {
    }

    public Tblprivilegio(Tblrol tblrol, Tblobjeto tblobjeto, boolean permiso) {
       this.tblrol = tblrol;
       this.tblobjeto = tblobjeto;
       this.permiso = permiso;
    }
   
    public Short getIdPrivilegio() {
        return this.idPrivilegio;
    }
    
    public void setIdPrivilegio(Short idPrivilegio) {
        this.idPrivilegio = idPrivilegio;
    }
    public Tblrol getTblrol() {
        return this.tblrol;
    }
    
    public void setTblrol(Tblrol tblrol) {
        this.tblrol = tblrol;
    }
    public Tblobjeto getTblobjeto() {
        return this.tblobjeto;
    }
    
    public void setTblobjeto(Tblobjeto tblobjeto) {
        this.tblobjeto = tblobjeto;
    }
    public boolean isPermiso() {
        return this.permiso;
    }
    
    public void setPermiso(boolean permiso) {
        this.permiso = permiso;
    }




}


