package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tblpermiso generated by hbm2java
 */
public class Tblpermiso  implements java.io.Serializable {


     private Long idPermiso;
     private Tblempleado tblempleado;
     private Date fechaSolicitud;
     private Date fechaInicio;
     private Date fechaFinal;
     private String observaciones;
     private String motivo;
     private String tipoLicencia;
     private boolean goceSueldo;
     private boolean tipoPermiso;
     private boolean jornadaCompleta;

    public Tblpermiso() {
    }

	
    public Tblpermiso(Tblempleado tblempleado, Date fechaSolicitud, Date fechaInicio, Date fechaFinal, String motivo, String tipoLicencia, boolean goceSueldo, boolean tipoPermiso, boolean jornadaCompleta) {
        this.tblempleado = tblempleado;
        this.fechaSolicitud = fechaSolicitud;
        this.fechaInicio = fechaInicio;
        this.fechaFinal = fechaFinal;
        this.motivo = motivo;
        this.tipoLicencia = tipoLicencia;
        this.goceSueldo = goceSueldo;
        this.tipoPermiso = tipoPermiso;
        this.jornadaCompleta = jornadaCompleta;
    }
    public Tblpermiso(Tblempleado tblempleado, Date fechaSolicitud, Date fechaInicio, Date fechaFinal, String observaciones, String motivo, String tipoLicencia, boolean goceSueldo, boolean tipoPermiso, boolean jornadaCompleta) {
       this.tblempleado = tblempleado;
       this.fechaSolicitud = fechaSolicitud;
       this.fechaInicio = fechaInicio;
       this.fechaFinal = fechaFinal;
       this.observaciones = observaciones;
       this.motivo = motivo;
       this.tipoLicencia = tipoLicencia;
       this.goceSueldo = goceSueldo;
       this.tipoPermiso = tipoPermiso;
       this.jornadaCompleta = jornadaCompleta;
    }
   
    public Long getIdPermiso() {
        return this.idPermiso;
    }
    
    public void setIdPermiso(Long idPermiso) {
        this.idPermiso = idPermiso;
    }
    public Tblempleado getTblempleado() {
        return this.tblempleado;
    }
    
    public void setTblempleado(Tblempleado tblempleado) {
        this.tblempleado = tblempleado;
    }
    public Date getFechaSolicitud() {
        return this.fechaSolicitud;
    }
    
    public void setFechaSolicitud(Date fechaSolicitud) {
        this.fechaSolicitud = fechaSolicitud;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public String getTipoLicencia() {
        return this.tipoLicencia;
    }
    
    public void setTipoLicencia(String tipoLicencia) {
        this.tipoLicencia = tipoLicencia;
    }
    public boolean isGoceSueldo() {
        return this.goceSueldo;
    }
    
    public void setGoceSueldo(boolean goceSueldo) {
        this.goceSueldo = goceSueldo;
    }
    public boolean isTipoPermiso() {
        return this.tipoPermiso;
    }
    
    public void setTipoPermiso(boolean tipoPermiso) {
        this.tipoPermiso = tipoPermiso;
    }
    public boolean isJornadaCompleta() {
        return this.jornadaCompleta;
    }
    
    public void setJornadaCompleta(boolean jornadaCompleta) {
        this.jornadaCompleta = jornadaCompleta;
    }




}


