package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA



/**
 * Tblproduccion generated by hbm2java
 */
public class Tblproduccion  implements java.io.Serializable {


     private Long idProduccion;
     private Tblparametro tblparametro;
     private TblexamenOrden tblexamenOrden;
     private String valor;

    public Tblproduccion() {
    }

    public Tblproduccion(Tblparametro tblparametro, TblexamenOrden tblexamenOrden, String valor) {
       this.tblparametro = tblparametro;
       this.tblexamenOrden = tblexamenOrden;
       this.valor = valor;
    }
   
    public Long getIdProduccion() {
        return this.idProduccion;
    }
    
    public void setIdProduccion(Long idProduccion) {
        this.idProduccion = idProduccion;
    }
    public Tblparametro getTblparametro() {
        return this.tblparametro;
    }
    
    public void setTblparametro(Tblparametro tblparametro) {
        this.tblparametro = tblparametro;
    }
    public TblexamenOrden getTblexamenOrden() {
        return this.tblexamenOrden;
    }
    
    public void setTblexamenOrden(TblexamenOrden tblexamenOrden) {
        this.tblexamenOrden = tblexamenOrden;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }




}


