package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tblprocedenciaarticulo generated by hbm2java
 */
public class Tblprocedenciaarticulo  implements java.io.Serializable {


     private Short idProcedencia;
     private String lugarProcedencia;
     private Set tblentradas = new HashSet(0);

    public Tblprocedenciaarticulo() {
    }

	
    public Tblprocedenciaarticulo(String lugarProcedencia) {
        this.lugarProcedencia = lugarProcedencia;
    }
    public Tblprocedenciaarticulo(String lugarProcedencia, Set tblentradas) {
       this.lugarProcedencia = lugarProcedencia;
       this.tblentradas = tblentradas;
    }
   
    public Short getIdProcedencia() {
        return this.idProcedencia;
    }
    
    public void setIdProcedencia(Short idProcedencia) {
        this.idProcedencia = idProcedencia;
    }
    public String getLugarProcedencia() {
        return this.lugarProcedencia;
    }
    
    public void setLugarProcedencia(String lugarProcedencia) {
        this.lugarProcedencia = lugarProcedencia;
    }
    public Set getTblentradas() {
        return this.tblentradas;
    }
    
    public void setTblentradas(Set tblentradas) {
        this.tblentradas = tblentradas;
    }




}


