package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA



/**
 * Tblpagina generated by hbm2java
 */
public class Tblpagina  implements java.io.Serializable {


     private Short idPagina;
     private Tblobjeto tblobjeto;
     private String url;
     private String titulo;
     private String descripcion;

    public Tblpagina() {
    }

	
    public Tblpagina(Tblobjeto tblobjeto, String url) {
        this.tblobjeto = tblobjeto;
        this.url = url;
    }
    public Tblpagina(Tblobjeto tblobjeto, String url, String titulo, String descripcion) {
       this.tblobjeto = tblobjeto;
       this.url = url;
       this.titulo = titulo;
       this.descripcion = descripcion;
    }
   
    public Short getIdPagina() {
        return this.idPagina;
    }
    
    public void setIdPagina(Short idPagina) {
        this.idPagina = idPagina;
    }
    public Tblobjeto getTblobjeto() {
        return this.tblobjeto;
    }
    
    public void setTblobjeto(Tblobjeto tblobjeto) {
        this.tblobjeto = tblobjeto;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


