package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tblparametro generated by hbm2java
 */
public class Tblparametro  implements java.io.Serializable {


     private Integer idParametro;
     private Tblexamen tblexamen;
     private Tblunidadmedida tblunidadmedida;
     private String nombreParametro;
     private String tipoParametro;
     private double valorMinimo;
     private double valorMaximo;
     private double valorNormal;
     private boolean fijo;
     private Set tblproduccions = new HashSet(0);

    public Tblparametro() {
    }

	
    public Tblparametro(Tblexamen tblexamen, String nombreParametro, String tipoParametro, double valorMinimo, double valorMaximo, double valorNormal, boolean fijo) {
        this.tblexamen = tblexamen;
        this.nombreParametro = nombreParametro;
        this.tipoParametro = tipoParametro;
        this.valorMinimo = valorMinimo;
        this.valorMaximo = valorMaximo;
        this.valorNormal = valorNormal;
        this.fijo = fijo;
    }
    public Tblparametro(Tblexamen tblexamen, Tblunidadmedida tblunidadmedida, String nombreParametro, String tipoParametro, double valorMinimo, double valorMaximo, double valorNormal, boolean fijo, Set tblproduccions) {
       this.tblexamen = tblexamen;
       this.tblunidadmedida = tblunidadmedida;
       this.nombreParametro = nombreParametro;
       this.tipoParametro = tipoParametro;
       this.valorMinimo = valorMinimo;
       this.valorMaximo = valorMaximo;
       this.valorNormal = valorNormal;
       this.fijo = fijo;
       this.tblproduccions = tblproduccions;
    }
   
    public Integer getIdParametro() {
        return this.idParametro;
    }
    
    public void setIdParametro(Integer idParametro) {
        this.idParametro = idParametro;
    }
    public Tblexamen getTblexamen() {
        return this.tblexamen;
    }
    
    public void setTblexamen(Tblexamen tblexamen) {
        this.tblexamen = tblexamen;
    }
    public Tblunidadmedida getTblunidadmedida() {
        return this.tblunidadmedida;
    }
    
    public void setTblunidadmedida(Tblunidadmedida tblunidadmedida) {
        this.tblunidadmedida = tblunidadmedida;
    }
    public String getNombreParametro() {
        return this.nombreParametro;
    }
    
    public void setNombreParametro(String nombreParametro) {
        this.nombreParametro = nombreParametro;
    }
    public String getTipoParametro() {
        return this.tipoParametro;
    }
    
    public void setTipoParametro(String tipoParametro) {
        this.tipoParametro = tipoParametro;
    }
    public double getValorMinimo() {
        return this.valorMinimo;
    }
    
    public void setValorMinimo(double valorMinimo) {
        this.valorMinimo = valorMinimo;
    }
    public double getValorMaximo() {
        return this.valorMaximo;
    }
    
    public void setValorMaximo(double valorMaximo) {
        this.valorMaximo = valorMaximo;
    }
    public double getValorNormal() {
        return this.valorNormal;
    }
    
    public void setValorNormal(double valorNormal) {
        this.valorNormal = valorNormal;
    }
    public boolean isFijo() {
        return this.fijo;
    }
    
    public void setFijo(boolean fijo) {
        this.fijo = fijo;
    }
    public Set getTblproduccions() {
        return this.tblproduccions;
    }
    
    public void setTblproduccions(Set tblproduccions) {
        this.tblproduccions = tblproduccions;
    }




}


