package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblpedido generated by hbm2java
 */
public class Tblpedido  implements java.io.Serializable {


     private Integer idPedido;
     private Date fecha;
     private Set tbldetallepedidos = new HashSet(0);

    public Tblpedido() {
    }

	
    public Tblpedido(Date fecha) {
        this.fecha = fecha;
    }
    public Tblpedido(Date fecha, Set tbldetallepedidos) {
       this.fecha = fecha;
       this.tbldetallepedidos = tbldetallepedidos;
    }
   
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getTbldetallepedidos() {
        return this.tbldetallepedidos;
    }
    
    public void setTbldetallepedidos(Set tbldetallepedidos) {
        this.tbldetallepedidos = tbldetallepedidos;
    }




}


