package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tblpuesto generated by hbm2java
 */
public class Tblpuesto  implements java.io.Serializable {


     private Short idPuesto;
     private String nombrePuesto;
     private double sueldoBase;
     private Set tblpuestoempleados = new HashSet(0);

    public Tblpuesto() {
    }

	
    public Tblpuesto(String nombrePuesto, double sueldoBase) {
        this.nombrePuesto = nombrePuesto;
        this.sueldoBase = sueldoBase;
    }
    public Tblpuesto(String nombrePuesto, double sueldoBase, Set tblpuestoempleados) {
       this.nombrePuesto = nombrePuesto;
       this.sueldoBase = sueldoBase;
       this.tblpuestoempleados = tblpuestoempleados;
    }
   
    public Short getIdPuesto() {
        return this.idPuesto;
    }
    
    public void setIdPuesto(Short idPuesto) {
        this.idPuesto = idPuesto;
    }
    public String getNombrePuesto() {
        return this.nombrePuesto;
    }
    
    public void setNombrePuesto(String nombrePuesto) {
        this.nombrePuesto = nombrePuesto;
    }
    public double getSueldoBase() {
        return this.sueldoBase;
    }
    
    public void setSueldoBase(double sueldoBase) {
        this.sueldoBase = sueldoBase;
    }
    public Set getTblpuestoempleados() {
        return this.tblpuestoempleados;
    }
    
    public void setTblpuestoempleados(Set tblpuestoempleados) {
        this.tblpuestoempleados = tblpuestoempleados;
    }




}


