package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblpersona generated by hbm2java
 */
public class Tblpersona  implements java.io.Serializable {


     private Long idPersona;
     private String primerNombre;
     private String segundoNombre;
     private String primerApellido;
     private String segundoApellido;
     private Date fechaNacimiento;
     private Character sexo;
     private String tipoSangre;
     private String tipoDocId;
     private String docId;
     private String estadoCivil;
     private Set tblentregaresultados = new HashSet(0);
     private Set tblpacientes = new HashSet(0);
     private Set tbllugtrabajos = new HashSet(0);
     private Set tbldonantes = new HashSet(0);
     private Set tblmedicos = new HashSet(0);
     private Set tbldomicilios = new HashSet(0);
     private Set tbldirectors = new HashSet(0);
     private Set tblempleados = new HashSet(0);

    public Tblpersona() {
    }

	
    public Tblpersona(String primerNombre, String primerApellido) {
        this.primerNombre = primerNombre;
        this.primerApellido = primerApellido;
    }
    public Tblpersona(String primerNombre, String segundoNombre, String primerApellido, String segundoApellido, Date fechaNacimiento, Character sexo, String tipoSangre, String tipoDocId, String docId, String estadoCivil, Set tblentregaresultados, Set tblpacientes, Set tbllugtrabajos, Set tbldonantes, Set tblmedicos, Set tbldomicilios, Set tbldirectors, Set tblempleados) {
       this.primerNombre = primerNombre;
       this.segundoNombre = segundoNombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.fechaNacimiento = fechaNacimiento;
       this.sexo = sexo;
       this.tipoSangre = tipoSangre;
       this.tipoDocId = tipoDocId;
       this.docId = docId;
       this.estadoCivil = estadoCivil;
       this.tblentregaresultados = tblentregaresultados;
       this.tblpacientes = tblpacientes;
       this.tbllugtrabajos = tbllugtrabajos;
       this.tbldonantes = tbldonantes;
       this.tblmedicos = tblmedicos;
       this.tbldomicilios = tbldomicilios;
       this.tbldirectors = tbldirectors;
       this.tblempleados = tblempleados;
    }
   
    public Long getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Long idPersona) {
        this.idPersona = idPersona;
    }
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }
    public String getSegundoNombre() {
        return this.segundoNombre;
    }
    
    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }
    public String getTipoSangre() {
        return this.tipoSangre;
    }
    
    public void setTipoSangre(String tipoSangre) {
        this.tipoSangre = tipoSangre;
    }
    public String getTipoDocId() {
        return this.tipoDocId;
    }
    
    public void setTipoDocId(String tipoDocId) {
        this.tipoDocId = tipoDocId;
    }
    public String getDocId() {
        return this.docId;
    }
    
    public void setDocId(String docId) {
        this.docId = docId;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public Set getTblentregaresultados() {
        return this.tblentregaresultados;
    }
    
    public void setTblentregaresultados(Set tblentregaresultados) {
        this.tblentregaresultados = tblentregaresultados;
    }
    public Set getTblpacientes() {
        return this.tblpacientes;
    }
    
    public void setTblpacientes(Set tblpacientes) {
        this.tblpacientes = tblpacientes;
    }
    public Set getTbllugtrabajos() {
        return this.tbllugtrabajos;
    }
    
    public void setTbllugtrabajos(Set tbllugtrabajos) {
        this.tbllugtrabajos = tbllugtrabajos;
    }
    public Set getTbldonantes() {
        return this.tbldonantes;
    }
    
    public void setTbldonantes(Set tbldonantes) {
        this.tbldonantes = tbldonantes;
    }
    public Set getTblmedicos() {
        return this.tblmedicos;
    }
    
    public void setTblmedicos(Set tblmedicos) {
        this.tblmedicos = tblmedicos;
    }
    public Set getTbldomicilios() {
        return this.tbldomicilios;
    }
    
    public void setTbldomicilios(Set tbldomicilios) {
        this.tbldomicilios = tbldomicilios;
    }
    public Set getTbldirectors() {
        return this.tbldirectors;
    }
    
    public void setTbldirectors(Set tbldirectors) {
        this.tbldirectors = tbldirectors;
    }
    public Set getTblempleados() {
        return this.tblempleados;
    }
    
    public void setTblempleados(Set tblempleados) {
        this.tblempleados = tblempleados;
    }




}


