package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblplanificaciontrabajo generated by hbm2java
 */
public class Tblplanificaciontrabajo  implements java.io.Serializable {


     private Long idPlanificacionTrabajo;
     private Tblcargalaboral tblcargalaboral;
     private Tblempleado tblempleado;
     private Date fechaEntrada;
     private Date fechaSalida;
     private short horaDuracion;
     private short minsDuracion;
     private Set tblcambioturnos = new HashSet(0);
     private Set tblseccions = new HashSet(0);

    public Tblplanificaciontrabajo() {
    }

	
    public Tblplanificaciontrabajo(Tblcargalaboral tblcargalaboral, Tblempleado tblempleado, Date fechaEntrada, Date fechaSalida, short horaDuracion, short minsDuracion) {
        this.tblcargalaboral = tblcargalaboral;
        this.tblempleado = tblempleado;
        this.fechaEntrada = fechaEntrada;
        this.fechaSalida = fechaSalida;
        this.horaDuracion = horaDuracion;
        this.minsDuracion = minsDuracion;
    }
    public Tblplanificaciontrabajo(Tblcargalaboral tblcargalaboral, Tblempleado tblempleado, Date fechaEntrada, Date fechaSalida, short horaDuracion, short minsDuracion, Set tblcambioturnos, Set tblseccions) {
       this.tblcargalaboral = tblcargalaboral;
       this.tblempleado = tblempleado;
       this.fechaEntrada = fechaEntrada;
       this.fechaSalida = fechaSalida;
       this.horaDuracion = horaDuracion;
       this.minsDuracion = minsDuracion;
       this.tblcambioturnos = tblcambioturnos;
       this.tblseccions = tblseccions;
    }
   
    public Long getIdPlanificacionTrabajo() {
        return this.idPlanificacionTrabajo;
    }
    
    public void setIdPlanificacionTrabajo(Long idPlanificacionTrabajo) {
        this.idPlanificacionTrabajo = idPlanificacionTrabajo;
    }
    public Tblcargalaboral getTblcargalaboral() {
        return this.tblcargalaboral;
    }
    
    public void setTblcargalaboral(Tblcargalaboral tblcargalaboral) {
        this.tblcargalaboral = tblcargalaboral;
    }
    public Tblempleado getTblempleado() {
        return this.tblempleado;
    }
    
    public void setTblempleado(Tblempleado tblempleado) {
        this.tblempleado = tblempleado;
    }
    public Date getFechaEntrada() {
        return this.fechaEntrada;
    }
    
    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }
    public short getHoraDuracion() {
        return this.horaDuracion;
    }
    
    public void setHoraDuracion(short horaDuracion) {
        this.horaDuracion = horaDuracion;
    }
    public short getMinsDuracion() {
        return this.minsDuracion;
    }
    
    public void setMinsDuracion(short minsDuracion) {
        this.minsDuracion = minsDuracion;
    }
    public Set getTblcambioturnos() {
        return this.tblcambioturnos;
    }
    
    public void setTblcambioturnos(Set tblcambioturnos) {
        this.tblcambioturnos = tblcambioturnos;
    }
    public Set getTblseccions() {
        return this.tblseccions;
    }
    
    public void setTblseccions(Set tblseccions) {
        this.tblseccions = tblseccions;
    }




}


