package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tblpaciente generated by hbm2java
 */
public class Tblpaciente  implements java.io.Serializable {


     private Long idPaciente;
     private Tblpersona tblpersona;
     private String numExpediente;
     private Set tblevaluaciondonantes = new HashSet(0);
     private Set tblordens = new HashSet(0);
     private Set tbltransfusions = new HashSet(0);

    public Tblpaciente() {
    }

	
    public Tblpaciente(Tblpersona tblpersona, String numExpediente) {
        this.tblpersona = tblpersona;
        this.numExpediente = numExpediente;
    }
    public Tblpaciente(Tblpersona tblpersona, String numExpediente, Set tblevaluaciondonantes, Set tblordens, Set tbltransfusions) {
       this.tblpersona = tblpersona;
       this.numExpediente = numExpediente;
       this.tblevaluaciondonantes = tblevaluaciondonantes;
       this.tblordens = tblordens;
       this.tbltransfusions = tbltransfusions;
    }
   
    public Long getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Long idPaciente) {
        this.idPaciente = idPaciente;
    }
    public Tblpersona getTblpersona() {
        return this.tblpersona;
    }
    
    public void setTblpersona(Tblpersona tblpersona) {
        this.tblpersona = tblpersona;
    }
    public String getNumExpediente() {
        return this.numExpediente;
    }
    
    public void setNumExpediente(String numExpediente) {
        this.numExpediente = numExpediente;
    }
    public Set getTblevaluaciondonantes() {
        return this.tblevaluaciondonantes;
    }
    
    public void setTblevaluaciondonantes(Set tblevaluaciondonantes) {
        this.tblevaluaciondonantes = tblevaluaciondonantes;
    }
    public Set getTblordens() {
        return this.tblordens;
    }
    
    public void setTblordens(Set tblordens) {
        this.tblordens = tblordens;
    }
    public Set getTbltransfusions() {
        return this.tbltransfusions;
    }
    
    public void setTbltransfusions(Set tbltransfusions) {
        this.tbltransfusions = tbltransfusions;
    }




}


