package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblpuestoempleado generated by hbm2java
 */
public class Tblpuestoempleado  implements java.io.Serializable {


     private Integer idPuestoEmpleado;
     private Tblpuesto tblpuesto;
     private Tblempleado tblempleado;
     private Date fechaAsignacion;
     private String unidadPresupuestaria;
     private String partida;
     private String lineaTrabajo;
     private boolean estado;
     private Set tblsueldoempleados = new HashSet(0);

    public Tblpuestoempleado() {
    }

	
    public Tblpuestoempleado(Tblpuesto tblpuesto, Tblempleado tblempleado, Date fechaAsignacion, boolean estado) {
        this.tblpuesto = tblpuesto;
        this.tblempleado = tblempleado;
        this.fechaAsignacion = fechaAsignacion;
        this.estado = estado;
    }
    public Tblpuestoempleado(Tblpuesto tblpuesto, Tblempleado tblempleado, Date fechaAsignacion, String unidadPresupuestaria, String partida, String lineaTrabajo, boolean estado, Set tblsueldoempleados) {
       this.tblpuesto = tblpuesto;
       this.tblempleado = tblempleado;
       this.fechaAsignacion = fechaAsignacion;
       this.unidadPresupuestaria = unidadPresupuestaria;
       this.partida = partida;
       this.lineaTrabajo = lineaTrabajo;
       this.estado = estado;
       this.tblsueldoempleados = tblsueldoempleados;
    }
   
    public Integer getIdPuestoEmpleado() {
        return this.idPuestoEmpleado;
    }
    
    public void setIdPuestoEmpleado(Integer idPuestoEmpleado) {
        this.idPuestoEmpleado = idPuestoEmpleado;
    }
    public Tblpuesto getTblpuesto() {
        return this.tblpuesto;
    }
    
    public void setTblpuesto(Tblpuesto tblpuesto) {
        this.tblpuesto = tblpuesto;
    }
    public Tblempleado getTblempleado() {
        return this.tblempleado;
    }
    
    public void setTblempleado(Tblempleado tblempleado) {
        this.tblempleado = tblempleado;
    }
    public Date getFechaAsignacion() {
        return this.fechaAsignacion;
    }
    
    public void setFechaAsignacion(Date fechaAsignacion) {
        this.fechaAsignacion = fechaAsignacion;
    }
    public String getUnidadPresupuestaria() {
        return this.unidadPresupuestaria;
    }
    
    public void setUnidadPresupuestaria(String unidadPresupuestaria) {
        this.unidadPresupuestaria = unidadPresupuestaria;
    }
    public String getPartida() {
        return this.partida;
    }
    
    public void setPartida(String partida) {
        this.partida = partida;
    }
    public String getLineaTrabajo() {
        return this.lineaTrabajo;
    }
    
    public void setLineaTrabajo(String lineaTrabajo) {
        this.lineaTrabajo = lineaTrabajo;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getTblsueldoempleados() {
        return this.tblsueldoempleados;
    }
    
    public void setTblsueldoempleados(Set tblsueldoempleados) {
        this.tblsueldoempleados = tblsueldoempleados;
    }




}


