package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tblrol generated by hbm2java
 */
public class Tblrol  implements java.io.Serializable {


     private Short idRol;
     private String nombreRol;
     private Set tblusuarios = new HashSet(0);
     private Set tblprivilegios = new HashSet(0);

    public Tblrol() {
    }

	
    public Tblrol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Tblrol(String nombreRol, Set tblusuarios, Set tblprivilegios) {
       this.nombreRol = nombreRol;
       this.tblusuarios = tblusuarios;
       this.tblprivilegios = tblprivilegios;
    }
   
    public Short getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Short idRol) {
        this.idRol = idRol;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Set getTblusuarios() {
        return this.tblusuarios;
    }
    
    public void setTblusuarios(Set tblusuarios) {
        this.tblusuarios = tblusuarios;
    }
    public Set getTblprivilegios() {
        return this.tblprivilegios;
    }
    
    public void setTblprivilegios(Set tblprivilegios) {
        this.tblprivilegios = tblprivilegios;
    }




}


