package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TblrespuestaCuestionario generated by hbm2java
 */
public class TblrespuestaCuestionario  implements java.io.Serializable {


     private Long idRespuesta;
     private TblcuestionarioEvaluacion tblcuestionarioEvaluacion;
     private Tblevaluaciondonante tblevaluaciondonante;
     private Boolean respuesta;
     private Set tblrespuestaCriterios = new HashSet(0);

    public TblrespuestaCuestionario() {
    }

	
    public TblrespuestaCuestionario(TblcuestionarioEvaluacion tblcuestionarioEvaluacion, Tblevaluaciondonante tblevaluaciondonante) {
        this.tblcuestionarioEvaluacion = tblcuestionarioEvaluacion;
        this.tblevaluaciondonante = tblevaluaciondonante;
    }
    public TblrespuestaCuestionario(TblcuestionarioEvaluacion tblcuestionarioEvaluacion, Tblevaluaciondonante tblevaluaciondonante, Boolean respuesta, Set tblrespuestaCriterios) {
       this.tblcuestionarioEvaluacion = tblcuestionarioEvaluacion;
       this.tblevaluaciondonante = tblevaluaciondonante;
       this.respuesta = respuesta;
       this.tblrespuestaCriterios = tblrespuestaCriterios;
    }
   
    public Long getIdRespuesta() {
        return this.idRespuesta;
    }
    
    public void setIdRespuesta(Long idRespuesta) {
        this.idRespuesta = idRespuesta;
    }
    public TblcuestionarioEvaluacion getTblcuestionarioEvaluacion() {
        return this.tblcuestionarioEvaluacion;
    }
    
    public void setTblcuestionarioEvaluacion(TblcuestionarioEvaluacion tblcuestionarioEvaluacion) {
        this.tblcuestionarioEvaluacion = tblcuestionarioEvaluacion;
    }
    public Tblevaluaciondonante getTblevaluaciondonante() {
        return this.tblevaluaciondonante;
    }
    
    public void setTblevaluaciondonante(Tblevaluaciondonante tblevaluaciondonante) {
        this.tblevaluaciondonante = tblevaluaciondonante;
    }
    public Boolean getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(Boolean respuesta) {
        this.respuesta = respuesta;
    }
    public Set getTblrespuestaCriterios() {
        return this.tblrespuestaCriterios;
    }
    
    public void setTblrespuestaCriterios(Set tblrespuestaCriterios) {
        this.tblrespuestaCriterios = tblrespuestaCriterios;
    }




}


