package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblresultado generated by hbm2java
 */
public class Tblresultado  implements java.io.Serializable {


     private Long idResultado;
     private Tbltiporesultado tbltiporesultado;
     private Tblempleado tblempleado;
     private TblexamenOrden tblexamenOrden;
     private Date fechaResultado;
     private Set tblincidencias = new HashSet(0);

    public Tblresultado() {
    }

	
    public Tblresultado(Tbltiporesultado tbltiporesultado, Tblempleado tblempleado, TblexamenOrden tblexamenOrden, Date fechaResultado) {
        this.tbltiporesultado = tbltiporesultado;
        this.tblempleado = tblempleado;
        this.tblexamenOrden = tblexamenOrden;
        this.fechaResultado = fechaResultado;
    }
    public Tblresultado(Tbltiporesultado tbltiporesultado, Tblempleado tblempleado, TblexamenOrden tblexamenOrden, Date fechaResultado, Set tblincidencias) {
       this.tbltiporesultado = tbltiporesultado;
       this.tblempleado = tblempleado;
       this.tblexamenOrden = tblexamenOrden;
       this.fechaResultado = fechaResultado;
       this.tblincidencias = tblincidencias;
    }
   
    public Long getIdResultado() {
        return this.idResultado;
    }
    
    public void setIdResultado(Long idResultado) {
        this.idResultado = idResultado;
    }
    public Tbltiporesultado getTbltiporesultado() {
        return this.tbltiporesultado;
    }
    
    public void setTbltiporesultado(Tbltiporesultado tbltiporesultado) {
        this.tbltiporesultado = tbltiporesultado;
    }
    public Tblempleado getTblempleado() {
        return this.tblempleado;
    }
    
    public void setTblempleado(Tblempleado tblempleado) {
        this.tblempleado = tblempleado;
    }
    public TblexamenOrden getTblexamenOrden() {
        return this.tblexamenOrden;
    }
    
    public void setTblexamenOrden(TblexamenOrden tblexamenOrden) {
        this.tblexamenOrden = tblexamenOrden;
    }
    public Date getFechaResultado() {
        return this.fechaResultado;
    }
    
    public void setFechaResultado(Date fechaResultado) {
        this.fechaResultado = fechaResultado;
    }
    public Set getTblincidencias() {
        return this.tblincidencias;
    }
    
    public void setTblincidencias(Set tblincidencias) {
        this.tblincidencias = tblincidencias;
    }




}


