package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA



/**
 * TblrespuestaCriterio generated by hbm2java
 */
public class TblrespuestaCriterio  implements java.io.Serializable {


     private Long idRespuestaCriterio;
     private TblrespuestaCuestionario tblrespuestaCuestionario;
     private Tblcriterio tblcriterio;
     private Boolean respuesta;
     private String observacion;

    public TblrespuestaCriterio() {
    }

	
    public TblrespuestaCriterio(TblrespuestaCuestionario tblrespuestaCuestionario, Tblcriterio tblcriterio) {
        this.tblrespuestaCuestionario = tblrespuestaCuestionario;
        this.tblcriterio = tblcriterio;
    }
    public TblrespuestaCriterio(TblrespuestaCuestionario tblrespuestaCuestionario, Tblcriterio tblcriterio, Boolean respuesta, String observacion) {
       this.tblrespuestaCuestionario = tblrespuestaCuestionario;
       this.tblcriterio = tblcriterio;
       this.respuesta = respuesta;
       this.observacion = observacion;
    }
   
    public Long getIdRespuestaCriterio() {
        return this.idRespuestaCriterio;
    }
    
    public void setIdRespuestaCriterio(Long idRespuestaCriterio) {
        this.idRespuestaCriterio = idRespuestaCriterio;
    }
    public TblrespuestaCuestionario getTblrespuestaCuestionario() {
        return this.tblrespuestaCuestionario;
    }
    
    public void setTblrespuestaCuestionario(TblrespuestaCuestionario tblrespuestaCuestionario) {
        this.tblrespuestaCuestionario = tblrespuestaCuestionario;
    }
    public Tblcriterio getTblcriterio() {
        return this.tblcriterio;
    }
    
    public void setTblcriterio(Tblcriterio tblcriterio) {
        this.tblcriterio = tblcriterio;
    }
    public Boolean getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(Boolean respuesta) {
        this.respuesta = respuesta;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


