package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tblsueldoempleado generated by hbm2java
 */
public class Tblsueldoempleado  implements java.io.Serializable {


     private Integer idSueldoEmpleado;
     private Tblpuestoempleado tblpuestoempleado;
     private Date fechaAsignacion;
     private double sueldo;
     private boolean estado;

    public Tblsueldoempleado() {
    }

    public Tblsueldoempleado(Tblpuestoempleado tblpuestoempleado, Date fechaAsignacion, double sueldo, boolean estado) {
       this.tblpuestoempleado = tblpuestoempleado;
       this.fechaAsignacion = fechaAsignacion;
       this.sueldo = sueldo;
       this.estado = estado;
    }
   
    public Integer getIdSueldoEmpleado() {
        return this.idSueldoEmpleado;
    }
    
    public void setIdSueldoEmpleado(Integer idSueldoEmpleado) {
        this.idSueldoEmpleado = idSueldoEmpleado;
    }
    public Tblpuestoempleado getTblpuestoempleado() {
        return this.tblpuestoempleado;
    }
    
    public void setTblpuestoempleado(Tblpuestoempleado tblpuestoempleado) {
        this.tblpuestoempleado = tblpuestoempleado;
    }
    public Date getFechaAsignacion() {
        return this.fechaAsignacion;
    }
    
    public void setFechaAsignacion(Date fechaAsignacion) {
        this.fechaAsignacion = fechaAsignacion;
    }
    public double getSueldo() {
        return this.sueldo;
    }
    
    public void setSueldo(double sueldo) {
        this.sueldo = sueldo;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


