package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblsolicitudcambioturno generated by hbm2java
 */
public class Tblsolicitudcambioturno  implements java.io.Serializable {


     private Long idSolicitud;
     private Date fechaSolicitud;
     private String motivo;
     private int tiempoSolicitado;
     private Date fechaSolicitada;
     private Date horaInicioSolicitada;
     private Date horaFinalSolicitada;
     private int tiempoResposicion;
     private Date fechaReposicion;
     private Date horaInicioReposicion;
     private Date horaFinalReposicion;
     private String servicioReposicion;
     private Set tblcambioturnos = new HashSet(0);

    public Tblsolicitudcambioturno() {
    }

	
    public Tblsolicitudcambioturno(Date fechaSolicitud, String motivo, int tiempoSolicitado, Date fechaSolicitada, int tiempoResposicion, Date fechaReposicion, Date horaFinalReposicion, String servicioReposicion) {
        this.fechaSolicitud = fechaSolicitud;
        this.motivo = motivo;
        this.tiempoSolicitado = tiempoSolicitado;
        this.fechaSolicitada = fechaSolicitada;
        this.tiempoResposicion = tiempoResposicion;
        this.fechaReposicion = fechaReposicion;
        this.horaFinalReposicion = horaFinalReposicion;
        this.servicioReposicion = servicioReposicion;
    }
    public Tblsolicitudcambioturno(Date fechaSolicitud, String motivo, int tiempoSolicitado, Date fechaSolicitada, Date horaInicioSolicitada, Date horaFinalSolicitada, int tiempoResposicion, Date fechaReposicion, Date horaInicioReposicion, Date horaFinalReposicion, String servicioReposicion, Set tblcambioturnos) {
       this.fechaSolicitud = fechaSolicitud;
       this.motivo = motivo;
       this.tiempoSolicitado = tiempoSolicitado;
       this.fechaSolicitada = fechaSolicitada;
       this.horaInicioSolicitada = horaInicioSolicitada;
       this.horaFinalSolicitada = horaFinalSolicitada;
       this.tiempoResposicion = tiempoResposicion;
       this.fechaReposicion = fechaReposicion;
       this.horaInicioReposicion = horaInicioReposicion;
       this.horaFinalReposicion = horaFinalReposicion;
       this.servicioReposicion = servicioReposicion;
       this.tblcambioturnos = tblcambioturnos;
    }
   
    public Long getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(Long idSolicitud) {
        this.idSolicitud = idSolicitud;
    }
    public Date getFechaSolicitud() {
        return this.fechaSolicitud;
    }
    
    public void setFechaSolicitud(Date fechaSolicitud) {
        this.fechaSolicitud = fechaSolicitud;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public int getTiempoSolicitado() {
        return this.tiempoSolicitado;
    }
    
    public void setTiempoSolicitado(int tiempoSolicitado) {
        this.tiempoSolicitado = tiempoSolicitado;
    }
    public Date getFechaSolicitada() {
        return this.fechaSolicitada;
    }
    
    public void setFechaSolicitada(Date fechaSolicitada) {
        this.fechaSolicitada = fechaSolicitada;
    }
    public Date getHoraInicioSolicitada() {
        return this.horaInicioSolicitada;
    }
    
    public void setHoraInicioSolicitada(Date horaInicioSolicitada) {
        this.horaInicioSolicitada = horaInicioSolicitada;
    }
    public Date getHoraFinalSolicitada() {
        return this.horaFinalSolicitada;
    }
    
    public void setHoraFinalSolicitada(Date horaFinalSolicitada) {
        this.horaFinalSolicitada = horaFinalSolicitada;
    }
    public int getTiempoResposicion() {
        return this.tiempoResposicion;
    }
    
    public void setTiempoResposicion(int tiempoResposicion) {
        this.tiempoResposicion = tiempoResposicion;
    }
    public Date getFechaReposicion() {
        return this.fechaReposicion;
    }
    
    public void setFechaReposicion(Date fechaReposicion) {
        this.fechaReposicion = fechaReposicion;
    }
    public Date getHoraInicioReposicion() {
        return this.horaInicioReposicion;
    }
    
    public void setHoraInicioReposicion(Date horaInicioReposicion) {
        this.horaInicioReposicion = horaInicioReposicion;
    }
    public Date getHoraFinalReposicion() {
        return this.horaFinalReposicion;
    }
    
    public void setHoraFinalReposicion(Date horaFinalReposicion) {
        this.horaFinalReposicion = horaFinalReposicion;
    }
    public String getServicioReposicion() {
        return this.servicioReposicion;
    }
    
    public void setServicioReposicion(String servicioReposicion) {
        this.servicioReposicion = servicioReposicion;
    }
    public Set getTblcambioturnos() {
        return this.tblcambioturnos;
    }
    
    public void setTblcambioturnos(Set tblcambioturnos) {
        this.tblcambioturnos = tblcambioturnos;
    }




}


