package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tblseccion generated by hbm2java
 */
public class Tblseccion  implements java.io.Serializable {


     private Short idSeccionLaboratorio;
     private String nombreSeccion;
     private String codigoSeccion;
     private String reinicioNumeroControl;
     private Set tblplanificaciontrabajos = new HashSet(0);
     private Set tblexamens = new HashSet(0);

    public Tblseccion() {
    }

	
    public Tblseccion(String nombreSeccion, String codigoSeccion, String reinicioNumeroControl) {
        this.nombreSeccion = nombreSeccion;
        this.codigoSeccion = codigoSeccion;
        this.reinicioNumeroControl = reinicioNumeroControl;
    }
    public Tblseccion(String nombreSeccion, String codigoSeccion, String reinicioNumeroControl, Set tblplanificaciontrabajos, Set tblexamens) {
       this.nombreSeccion = nombreSeccion;
       this.codigoSeccion = codigoSeccion;
       this.reinicioNumeroControl = reinicioNumeroControl;
       this.tblplanificaciontrabajos = tblplanificaciontrabajos;
       this.tblexamens = tblexamens;
    }
   
    public Short getIdSeccionLaboratorio() {
        return this.idSeccionLaboratorio;
    }
    
    public void setIdSeccionLaboratorio(Short idSeccionLaboratorio) {
        this.idSeccionLaboratorio = idSeccionLaboratorio;
    }
    public String getNombreSeccion() {
        return this.nombreSeccion;
    }
    
    public void setNombreSeccion(String nombreSeccion) {
        this.nombreSeccion = nombreSeccion;
    }
    public String getCodigoSeccion() {
        return this.codigoSeccion;
    }
    
    public void setCodigoSeccion(String codigoSeccion) {
        this.codigoSeccion = codigoSeccion;
    }
    public String getReinicioNumeroControl() {
        return this.reinicioNumeroControl;
    }
    
    public void setReinicioNumeroControl(String reinicioNumeroControl) {
        this.reinicioNumeroControl = reinicioNumeroControl;
    }
    public Set getTblplanificaciontrabajos() {
        return this.tblplanificaciontrabajos;
    }
    
    public void setTblplanificaciontrabajos(Set tblplanificaciontrabajos) {
        this.tblplanificaciontrabajos = tblplanificaciontrabajos;
    }
    public Set getTblexamens() {
        return this.tblexamens;
    }
    
    public void setTblexamens(Set tblexamens) {
        this.tblexamens = tblexamens;
    }




}


