package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA



/**
 * Tblsolicitudvih generated by hbm2java
 */
public class Tblsolicitudvih  implements java.io.Serializable {


     private Long idSolicitudVih;
     private Tblorden tblorden;
     private String motivo;

    public Tblsolicitudvih() {
    }

    public Tblsolicitudvih(Tblorden tblorden, String motivo) {
       this.tblorden = tblorden;
       this.motivo = motivo;
    }
   
    public Long getIdSolicitudVih() {
        return this.idSolicitudVih;
    }
    
    public void setIdSolicitudVih(Long idSolicitudVih) {
        this.idSolicitudVih = idSolicitudVih;
    }
    public Tblorden getTblorden() {
        return this.tblorden;
    }
    
    public void setTblorden(Tblorden tblorden) {
        this.tblorden = tblorden;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }




}


