package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tbltiposervicio generated by hbm2java
 */
public class Tbltiposervicio  implements java.io.Serializable {


     private Short idTipoServicio;
     private Tblmodalidad tblmodalidad;
     private String codigoTipoServicio;
     private String nombreTipoServicio;
     private Set tblservicios = new HashSet(0);

    public Tbltiposervicio() {
    }

	
    public Tbltiposervicio(Tblmodalidad tblmodalidad, String codigoTipoServicio, String nombreTipoServicio) {
        this.tblmodalidad = tblmodalidad;
        this.codigoTipoServicio = codigoTipoServicio;
        this.nombreTipoServicio = nombreTipoServicio;
    }
    public Tbltiposervicio(Tblmodalidad tblmodalidad, String codigoTipoServicio, String nombreTipoServicio, Set tblservicios) {
       this.tblmodalidad = tblmodalidad;
       this.codigoTipoServicio = codigoTipoServicio;
       this.nombreTipoServicio = nombreTipoServicio;
       this.tblservicios = tblservicios;
    }
   
    public Short getIdTipoServicio() {
        return this.idTipoServicio;
    }
    
    public void setIdTipoServicio(Short idTipoServicio) {
        this.idTipoServicio = idTipoServicio;
    }
    public Tblmodalidad getTblmodalidad() {
        return this.tblmodalidad;
    }
    
    public void setTblmodalidad(Tblmodalidad tblmodalidad) {
        this.tblmodalidad = tblmodalidad;
    }
    public String getCodigoTipoServicio() {
        return this.codigoTipoServicio;
    }
    
    public void setCodigoTipoServicio(String codigoTipoServicio) {
        this.codigoTipoServicio = codigoTipoServicio;
    }
    public String getNombreTipoServicio() {
        return this.nombreTipoServicio;
    }
    
    public void setNombreTipoServicio(String nombreTipoServicio) {
        this.nombreTipoServicio = nombreTipoServicio;
    }
    public Set getTblservicios() {
        return this.tblservicios;
    }
    
    public void setTblservicios(Set tblservicios) {
        this.tblservicios = tblservicios;
    }




}


