package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tbltransfusion generated by hbm2java
 */
public class Tbltransfusion  implements java.io.Serializable {


     private Long idTransfusion;
     private Tblempleado tblempleado;
     private Tbldonante tbldonante;
     private Tblpaciente tblpaciente;
     private long idBancoSangre;
     private String tipComponenteSanguineo;
     private String responsableRegistro;
     private Date fechaTransfusion;
     private Set tbldomicilios = new HashSet(0);
     private Set tbllugtrabajos = new HashSet(0);

    public Tbltransfusion() {
    }

	
    public Tbltransfusion(Tblempleado tblempleado, Tbldonante tbldonante, Tblpaciente tblpaciente, long idBancoSangre, String tipComponenteSanguineo, String responsableRegistro, Date fechaTransfusion) {
        this.tblempleado = tblempleado;
        this.tbldonante = tbldonante;
        this.tblpaciente = tblpaciente;
        this.idBancoSangre = idBancoSangre;
        this.tipComponenteSanguineo = tipComponenteSanguineo;
        this.responsableRegistro = responsableRegistro;
        this.fechaTransfusion = fechaTransfusion;
    }
    public Tbltransfusion(Tblempleado tblempleado, Tbldonante tbldonante, Tblpaciente tblpaciente, long idBancoSangre, String tipComponenteSanguineo, String responsableRegistro, Date fechaTransfusion, Set tbldomicilios, Set tbllugtrabajos) {
       this.tblempleado = tblempleado;
       this.tbldonante = tbldonante;
       this.tblpaciente = tblpaciente;
       this.idBancoSangre = idBancoSangre;
       this.tipComponenteSanguineo = tipComponenteSanguineo;
       this.responsableRegistro = responsableRegistro;
       this.fechaTransfusion = fechaTransfusion;
       this.tbldomicilios = tbldomicilios;
       this.tbllugtrabajos = tbllugtrabajos;
    }
   
    public Long getIdTransfusion() {
        return this.idTransfusion;
    }
    
    public void setIdTransfusion(Long idTransfusion) {
        this.idTransfusion = idTransfusion;
    }
    public Tblempleado getTblempleado() {
        return this.tblempleado;
    }
    
    public void setTblempleado(Tblempleado tblempleado) {
        this.tblempleado = tblempleado;
    }
    public Tbldonante getTbldonante() {
        return this.tbldonante;
    }
    
    public void setTbldonante(Tbldonante tbldonante) {
        this.tbldonante = tbldonante;
    }
    public Tblpaciente getTblpaciente() {
        return this.tblpaciente;
    }
    
    public void setTblpaciente(Tblpaciente tblpaciente) {
        this.tblpaciente = tblpaciente;
    }
    public long getIdBancoSangre() {
        return this.idBancoSangre;
    }
    
    public void setIdBancoSangre(long idBancoSangre) {
        this.idBancoSangre = idBancoSangre;
    }
    public String getTipComponenteSanguineo() {
        return this.tipComponenteSanguineo;
    }
    
    public void setTipComponenteSanguineo(String tipComponenteSanguineo) {
        this.tipComponenteSanguineo = tipComponenteSanguineo;
    }
    public String getResponsableRegistro() {
        return this.responsableRegistro;
    }
    
    public void setResponsableRegistro(String responsableRegistro) {
        this.responsableRegistro = responsableRegistro;
    }
    public Date getFechaTransfusion() {
        return this.fechaTransfusion;
    }
    
    public void setFechaTransfusion(Date fechaTransfusion) {
        this.fechaTransfusion = fechaTransfusion;
    }
    public Set getTbldomicilios() {
        return this.tbldomicilios;
    }
    
    public void setTbldomicilios(Set tbldomicilios) {
        this.tbldomicilios = tbldomicilios;
    }
    public Set getTbllugtrabajos() {
        return this.tbllugtrabajos;
    }
    
    public void setTbllugtrabajos(Set tbllugtrabajos) {
        this.tbllugtrabajos = tbllugtrabajos;
    }




}


