package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tblusuario generated by hbm2java
 */
public class Tblusuario  implements java.io.Serializable {


     private Short idUsuario;
     private Tblempleado tblempleado;
     private String login;
     private String pass;
     private String estado;
     private Set tblrols = new HashSet(0);
     private Set tblbitacoras = new HashSet(0);

    public Tblusuario() {
    }

	
    public Tblusuario(Tblempleado tblempleado, String login, String pass, String estado) {
        this.tblempleado = tblempleado;
        this.login = login;
        this.pass = pass;
        this.estado = estado;
    }
    public Tblusuario(Tblempleado tblempleado, String login, String pass, String estado, Set tblrols, Set tblbitacoras) {
       this.tblempleado = tblempleado;
       this.login = login;
       this.pass = pass;
       this.estado = estado;
       this.tblrols = tblrols;
       this.tblbitacoras = tblbitacoras;
    }
   
    public Short getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Short idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Tblempleado getTblempleado() {
        return this.tblempleado;
    }
    
    public void setTblempleado(Tblempleado tblempleado) {
        this.tblempleado = tblempleado;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getTblrols() {
        return this.tblrols;
    }
    
    public void setTblrols(Set tblrols) {
        this.tblrols = tblrols;
    }
    public Set getTblbitacoras() {
        return this.tblbitacoras;
    }
    
    public void setTblbitacoras(Set tblbitacoras) {
        this.tblbitacoras = tblbitacoras;
    }




}


