package com.silac.model;
// Generated 01-29-2012 03:43:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tblunidadmedida generated by hbm2java
 */
public class Tblunidadmedida  implements java.io.Serializable {


     private Short idUnidadMedida;
     private String unidadMedida;
     private String abreviatura;
     private Set tblparametros = new HashSet(0);
     private Set tblarticulosForUnidadMinimoCompra = new HashSet(0);
     private Set tblarticulosForUnidadMinimoUso = new HashSet(0);

    public Tblunidadmedida() {
    }

	
    public Tblunidadmedida(String unidadMedida) {
        this.unidadMedida = unidadMedida;
    }
    public Tblunidadmedida(String unidadMedida, String abreviatura, Set tblparametros, Set tblarticulosForUnidadMinimoCompra, Set tblarticulosForUnidadMinimoUso) {
       this.unidadMedida = unidadMedida;
       this.abreviatura = abreviatura;
       this.tblparametros = tblparametros;
       this.tblarticulosForUnidadMinimoCompra = tblarticulosForUnidadMinimoCompra;
       this.tblarticulosForUnidadMinimoUso = tblarticulosForUnidadMinimoUso;
    }
   
    public Short getIdUnidadMedida() {
        return this.idUnidadMedida;
    }
    
    public void setIdUnidadMedida(Short idUnidadMedida) {
        this.idUnidadMedida = idUnidadMedida;
    }
    public String getUnidadMedida() {
        return this.unidadMedida;
    }
    
    public void setUnidadMedida(String unidadMedida) {
        this.unidadMedida = unidadMedida;
    }
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }
    public Set getTblparametros() {
        return this.tblparametros;
    }
    
    public void setTblparametros(Set tblparametros) {
        this.tblparametros = tblparametros;
    }
    public Set getTblarticulosForUnidadMinimoCompra() {
        return this.tblarticulosForUnidadMinimoCompra;
    }
    
    public void setTblarticulosForUnidadMinimoCompra(Set tblarticulosForUnidadMinimoCompra) {
        this.tblarticulosForUnidadMinimoCompra = tblarticulosForUnidadMinimoCompra;
    }
    public Set getTblarticulosForUnidadMinimoUso() {
        return this.tblarticulosForUnidadMinimoUso;
    }
    
    public void setTblarticulosForUnidadMinimoUso(Set tblarticulosForUnidadMinimoUso) {
        this.tblarticulosForUnidadMinimoUso = tblarticulosForUnidadMinimoUso;
    }




}


